// SPDX-License-Identifier: Apache-2.0
// SPDX-FileCopyrightText: 2026 Huang Rui <vowstar@gmail.com>

#include "common/qsocgeneratemanager.h"
#include "common/qsocgenerateprimitiveclock.h"
#include "common/qsocgenerateprimitivepower.h"
#include "common/qsocgenerateprimitivereset.h"
#include "common/qsocgeneratereportunconnected.h"
#include "common/qsocprojectmanager.h"
#include "qsoc_test.h"

#include <QCoreApplication>
#include <QDeadlineTimer>
#include <QDir>
#include <QFile>
#include <QFileInfo>
#include <QLockFile>
#include <QMap>
#include <QScopeGuard>
#include <QStringList>
#include <QTemporaryDir>
#include <QThread>
#include <QtTest>

#include <yaml-cpp/yaml.h>

#include <atomic>
#include <thread>
#include <vector>

namespace {

class Test : public QObject
{
    Q_OBJECT

private:
    QTemporaryDir      temporaryDirectory;
    QSocProjectManager projectManager;

    QByteArray readOutput(const QString &fileName)
    {
        QFile file(QDir(projectManager.getOutputPath()).filePath(fileName));
        if (!file.open(QIODevice::ReadOnly)) {
            return {};
        }
        return file.readAll();
    }

    bool generateArtifacts(QMap<QString, QByteArray> &artifacts)
    {
        const YAML::Node netlist = YAML::Load(R"(
port:
  source:
    direction: input
    type: logic
  result:
    direction: output
    type: logic
instance: {}
net: {}
comb:
  - out: result
    expr: source
)");

        QSocGenerateManager manager(nullptr, &projectManager);
        if (!manager.setNetlistData(netlist) || !manager.processNetlist()
            || !manager.generateVerilog("stable")
            || !manager.generateVerilogStub("stable_stub", {})) {
            return false;
        }

        QSocGenerateReportUnconnected                      reporter;
        QSocGenerateReportUnconnected::UnconnectedPortInfo port;
        port.instanceName = "u_source";
        port.moduleName   = "source";
        port.portName     = "unused";
        port.direction    = "input";
        port.type         = "logic";
        reporter.addUnconnectedPort(port);
        if (!reporter.generateReport(projectManager.getOutputPath(), "stable")) {
            return false;
        }

        const QString clockPath = QDir(projectManager.getOutputPath()).filePath("clock.typ");
        const QString resetPath = QDir(projectManager.getOutputPath()).filePath("reset.typ");
        const QString powerPath = QDir(projectManager.getOutputPath()).filePath("power.typ");

        QSocClockPrimitive clock;
        QSocResetPrimitive reset;
        QSocPowerPrimitive power;
        if (!clock.generateTypstDiagram({}, clockPath) || !reset.generateTypstDiagram({}, resetPath)
            || !power.generateTypstDiagram({}, powerPath)) {
            return false;
        }

        const QStringList fileNames{
            "stable.v", "stable_stub.v", "stable.nc.rpt", "clock.typ", "reset.typ", "power.typ"};
        for (const QString &fileName : fileNames) {
            const QByteArray content = readOutput(fileName);
            if (content.isEmpty()) {
                return false;
            }
            artifacts.insert(fileName, content);
        }
        return true;
    }

private slots:
    void initTestCase()
    {
        QVERIFY(temporaryDirectory.isValid());
        projectManager.setProjectName("reproducibility");
        projectManager.setCurrentPath(QDir(temporaryDirectory.path()).filePath("reproducibility"));
        QVERIFY(projectManager.mkpath());
    }

    void cleanupTestCase() { QVERIFY(QDir(temporaryDirectory.path()).removeRecursively()); }

    void applicationMetadataDoesNotChangeArtifacts()
    {
        const QString originalName    = QCoreApplication::applicationName();
        const QString originalVersion = QCoreApplication::applicationVersion();
        const auto    restoreMetadata = qScopeGuard([&]() {
            QCoreApplication::setApplicationName(originalName);
            QCoreApplication::setApplicationVersion(originalVersion);
        });

        QCoreApplication::setApplicationName("first-name");
        QCoreApplication::setApplicationVersion("1.2.3");
        QMap<QString, QByteArray> first;
        QVERIFY(generateArtifacts(first));

        QCoreApplication::setApplicationName("second-name");
        QCoreApplication::setApplicationVersion("9.8.7");
        QMap<QString, QByteArray> second;
        QVERIFY(generateArtifacts(second));

        QCOMPARE(second, first);
        for (auto it = first.cbegin(); it != first.cend(); ++it) {
            QVERIFY2(
                it.value().contains("Generated by QSoC."),
                qPrintable(it.key() + " lacks stable generator metadata"));
            QVERIFY(!it.value().contains("first-name"));
            QVERIFY(!it.value().contains("second-name"));
            QVERIFY(!it.value().contains("1.2.3"));
            QVERIFY(!it.value().contains("9.8.7"));
            QVERIFY(!it.value().contains("# Generated:"));
            QVERIFY(!it.value().contains('\r'));
        }
    }

    void concurrentProjectCreateHasOneWinner()
    {
        QTemporaryDir directory;
        QVERIFY(directory.isValid());
        const QString projectPath = QDir(directory.path()).filePath("project");

        std::atomic<int>          startState   = 0;
        std::atomic<int>          successCount = 0;
        std::vector<std::jthread> workers;
        workers.reserve(2);

        try {
            for (int worker = 0; worker < 2; ++worker) {
                workers.emplace_back([&]() {
                    QSocProjectManager manager;
                    manager.setCurrentPath(projectPath);
                    startState.wait(0);
                    if (startState.load() == 1 && manager.create("shared")) {
                        ++successCount;
                    }
                });
            }
        } catch (...) {
            startState.store(2);
            startState.notify_all();
            throw;
        }

        startState.store(1);
        startState.notify_all();
        workers.clear();

        QCOMPARE(successCount.load(), 1);
        QFile projectFile(QDir(projectPath).filePath("shared.soc_pro"));
        QVERIFY(projectFile.open(QIODevice::ReadOnly));
        QVERIFY(!projectFile.readAll().isEmpty());
        QVERIFY(!QFile::exists(projectFile.fileName() + ".lock"));
    }

    void heldProjectLockBlocksCreate()
    {
        QTemporaryDir directory;
        QVERIFY(directory.isValid());
        const QString projectPath = QDir(directory.path()).filePath("project");
        QVERIFY(QDir().mkpath(projectPath));

        const QString projectFilePath = QDir(projectPath).filePath("locked.soc_pro");
        QLockFile     projectLock(projectFilePath + ".lock");
        QVERIFY(projectLock.tryLock());

        QSocProjectManager manager;
        manager.setCurrentPath(projectPath);
        QVERIFY(!manager.create("locked"));
        QVERIFY(!QFileInfo::exists(projectFilePath));

        projectLock.unlock();
        QVERIFY(manager.create("locked"));
        QVERIFY(QFileInfo::exists(projectFilePath));
    }

    void projectNameCannotEscapeDirectory()
    {
        QTemporaryDir directory;
        QVERIFY(directory.isValid());
        const QString projectPath = QDir(directory.path()).filePath("project");

        QSocProjectManager manager;
        manager.setCurrentPath(projectPath);

        QVERIFY(!manager.create("../escaped"));
        QVERIFY(!QFileInfo::exists(QDir(directory.path()).filePath("escaped.soc_pro")));
        QVERIFY(!QFileInfo::exists(projectPath));
    }

    void existingMarkerLinkPreservesTarget()
    {
#ifndef Q_OS_UNIX
        QSKIP("This platform does not provide Unix symbolic-link semantics.");
#else
        QTemporaryDir directory;
        QVERIFY(directory.isValid());
        const QString projectPath = QDir(directory.path()).filePath("project");
        const QString busPath     = QDir(projectPath).filePath("bus");
        QVERIFY(QDir().mkpath(busPath));

        const QByteArray sentinelBytes(4096, 's');
        const QString    sentinelPath = QDir(directory.path()).filePath("sentinel");
        QFile            sentinelFile(sentinelPath);
        QVERIFY(sentinelFile.open(QIODevice::WriteOnly));
        QCOMPARE(sentinelFile.write(sentinelBytes), sentinelBytes.size());
        sentinelFile.close();

        const QString markerPath = QDir(busPath).filePath(".gitkeep");
        QVERIFY(QFile::link(sentinelPath, markerPath));

        QSocProjectManager manager;
        manager.setCurrentPath(projectPath);
        QVERIFY(manager.create("safe"));

        QVERIFY(sentinelFile.open(QIODevice::ReadOnly));
        QCOMPARE(sentinelFile.readAll(), sentinelBytes);
        QVERIFY(QFileInfo(markerPath).isSymLink());
#endif
    }

    void lateProjectLinkCannotClobberTarget()
    {
#ifndef Q_OS_UNIX
        QSKIP("This platform does not provide Unix symbolic-link semantics.");
#else
        QTemporaryDir directory;
        QVERIFY(directory.isValid());
        const QString projectPath = QDir(directory.path()).filePath("project");
        QString       deepBusPath = QDir(projectPath).filePath("bus");
        for (int depth = 0; depth < 256; ++depth) {
            deepBusPath = QDir(deepBusPath).filePath("d");
        }

        const QByteArray sentinelBytes(4096, 's');
        const QString    sentinelPath = QDir(directory.path()).filePath("sentinel");
        QFile            sentinelFile(sentinelPath);
        QVERIFY(sentinelFile.open(QIODevice::WriteOnly));
        QCOMPARE(sentinelFile.write(sentinelBytes), sentinelBytes.size());
        sentinelFile.close();

        std::atomic_bool createResult = false;
        std::atomic_bool finished     = false;
        std::jthread     worker([&]() {
            QSocProjectManager manager;
            manager.setCurrentPath(projectPath);
            manager.setBusPath(deepBusPath);
            createResult.store(manager.create("race"));
            finished.store(true);
        });

        const QString  gitignorePath  = QDir(projectPath).filePath(".gitignore");
        QDeadlineTimer waitForPrepare = QDeadlineTimer(5000);
        while (!QFileInfo::exists(gitignorePath) && !finished.load()
               && !waitForPrepare.hasExpired()) {
            QThread::yieldCurrentThread();
        }
        QVERIFY2(QFileInfo::exists(gitignorePath), "Project preparation did not start.");
        QVERIFY2(!finished.load(), "Project preparation completed before conflict injection.");

        const QString projectFilePath = QDir(projectPath).filePath("race.soc_pro");
        QVERIFY(QFile::link(sentinelPath, projectFilePath));
        worker.join();

        QVERIFY(!createResult.load());
        QVERIFY(sentinelFile.open(QIODevice::ReadOnly));
        QCOMPARE(sentinelFile.readAll(), sentinelBytes);
        QVERIFY(QFileInfo(projectFilePath).isSymLink());
#endif
    }

    void failedProjectSavePreservesTarget()
    {
        QTemporaryDir directory;
        QVERIFY(directory.isValid());

        QSocProjectManager manager;
        manager.setCurrentPath(directory.path());
        QVERIFY(manager.mkpath());

        const QString projectFilePath = QDir(directory.path()).filePath("blocked.soc_pro");
        QVERIFY(QDir().mkpath(projectFilePath));
        const QByteArray sentinelBytes(4096, 's');
        QFile            sentinelFile(QDir(projectFilePath).filePath("sentinel"));
        QVERIFY(sentinelFile.open(QIODevice::WriteOnly));
        QCOMPARE(sentinelFile.write(sentinelBytes), sentinelBytes.size());
        sentinelFile.close();

        const QStringList entriesBefore
            = QDir(directory.path())
                  .entryList(QDir::AllEntries | QDir::Hidden | QDir::NoDotAndDotDot, QDir::Name);
        QVERIFY(!manager.save("blocked"));

        const QStringList entriesAfter
            = QDir(directory.path())
                  .entryList(QDir::AllEntries | QDir::Hidden | QDir::NoDotAndDotDot, QDir::Name);
        QCOMPARE(entriesAfter, entriesBefore);
        QVERIFY(sentinelFile.open(QIODevice::ReadOnly));
        QCOMPARE(sentinelFile.readAll(), sentinelBytes);
    }
};

} // namespace

QSOC_TEST_MAIN(Test)
#include "test_qsocgeneratereproducibility.moc"
