// SPDX-License-Identifier: Apache-2.0
// SPDX-FileCopyrightText: 2026 Huang Rui <vowstar@gmail.com>

#include "common/qsocgeneratemanager.h"
#include "common/qsocgenerateprimitiveclock.h"
#include "common/qsocgenerateprimitivepower.h"
#include "common/qsocgenerateprimitivereset.h"
#include "common/qsocgeneratereportunconnected.h"
#include "common/qsocprojectmanager.h"
#include "qsoc_test.h"

#include <QCoreApplication>
#include <QDir>
#include <QFile>
#include <QMap>
#include <QScopeGuard>
#include <QStringList>
#include <QTemporaryDir>
#include <QtTest>

#include <yaml-cpp/yaml.h>

namespace {

class Test : public QObject
{
    Q_OBJECT

private:
    QTemporaryDir      temporaryDirectory;
    QSocProjectManager projectManager;

    QByteArray readOutput(const QString &fileName)
    {
        QFile file(QDir(projectManager.getOutputPath()).filePath(fileName));
        if (!file.open(QIODevice::ReadOnly)) {
            return {};
        }
        return file.readAll();
    }

    bool generateArtifacts(QMap<QString, QByteArray> &artifacts)
    {
        const YAML::Node netlist = YAML::Load(R"(
port:
  source:
    direction: input
    type: logic
  result:
    direction: output
    type: logic
instance: {}
net: {}
comb:
  - out: result
    expr: source
)");

        QSocGenerateManager manager(nullptr, &projectManager);
        if (!manager.setNetlistData(netlist) || !manager.processNetlist()
            || !manager.generateVerilog("stable")
            || !manager.generateVerilogStub("stable_stub", {})) {
            return false;
        }

        QSocGenerateReportUnconnected                      reporter;
        QSocGenerateReportUnconnected::UnconnectedPortInfo port;
        port.instanceName = "u_source";
        port.moduleName   = "source";
        port.portName     = "unused";
        port.direction    = "input";
        port.type         = "logic";
        reporter.addUnconnectedPort(port);
        if (!reporter.generateReport(projectManager.getOutputPath(), "stable")) {
            return false;
        }

        const QString clockPath = QDir(projectManager.getOutputPath()).filePath("clock.typ");
        const QString resetPath = QDir(projectManager.getOutputPath()).filePath("reset.typ");
        const QString powerPath = QDir(projectManager.getOutputPath()).filePath("power.typ");

        QSocClockPrimitive clock;
        QSocResetPrimitive reset;
        QSocPowerPrimitive power;
        if (!clock.generateTypstDiagram({}, clockPath) || !reset.generateTypstDiagram({}, resetPath)
            || !power.generateTypstDiagram({}, powerPath)) {
            return false;
        }

        const QStringList fileNames{
            "stable.v", "stable_stub.v", "stable.nc.rpt", "clock.typ", "reset.typ", "power.typ"};
        for (const QString &fileName : fileNames) {
            const QByteArray content = readOutput(fileName);
            if (content.isEmpty()) {
                return false;
            }
            artifacts.insert(fileName, content);
        }
        return true;
    }

private slots:
    void initTestCase()
    {
        QVERIFY(temporaryDirectory.isValid());
        projectManager.setProjectName("reproducibility");
        projectManager.setCurrentPath(QDir(temporaryDirectory.path()).filePath("reproducibility"));
        QVERIFY(projectManager.mkpath());
    }

    void applicationMetadataDoesNotChangeArtifacts()
    {
        const QString originalName    = QCoreApplication::applicationName();
        const QString originalVersion = QCoreApplication::applicationVersion();
        const auto    restoreMetadata = qScopeGuard([&]() {
            QCoreApplication::setApplicationName(originalName);
            QCoreApplication::setApplicationVersion(originalVersion);
        });

        QCoreApplication::setApplicationName("first-name");
        QCoreApplication::setApplicationVersion("1.2.3");
        QMap<QString, QByteArray> first;
        QVERIFY(generateArtifacts(first));

        QCoreApplication::setApplicationName("second-name");
        QCoreApplication::setApplicationVersion("9.8.7");
        QMap<QString, QByteArray> second;
        QVERIFY(generateArtifacts(second));

        QCOMPARE(second, first);
        for (auto it = first.cbegin(); it != first.cend(); ++it) {
            QVERIFY2(
                it.value().contains("Generated by QSoC."),
                qPrintable(it.key() + " lacks stable generator metadata"));
            QVERIFY(!it.value().contains("first-name"));
            QVERIFY(!it.value().contains("second-name"));
            QVERIFY(!it.value().contains("1.2.3"));
            QVERIFY(!it.value().contains("9.8.7"));
            QVERIFY(!it.value().contains("# Generated:"));
            QVERIFY(!it.value().contains('\r'));
        }
    }
};

} // namespace

QSOC_TEST_MAIN(Test)
#include "test_qsocgeneratereproducibility.moc"
