// SPDX-License-Identifier: Apache-2.0
// SPDX-FileCopyrightText: 2026 Huang Rui <vowstar@gmail.com>

#include "common/qsoccelltext.h"

namespace {

/* Each file is split into literals below the per-literal limit of some compilers */

const char *const clockCell[] = {
    R"v(/**
 * @file qsoc_cell_clock.v
 * @brief Template clock cells for QSoC clock primitives
 *
 * @details This file contains template clock cell modules for clock primitives.
 *          Auto-generated template file. Generated by qsoc.
 * CAUTION: Please replace the templates in this file
 *          with your technology's standard-cell implementations
 *          before using in production.
 */

`timescale 1ns / 1ps
/**
 * @brief Clock gate with scan and clock during reset policy
 *
 * @details POLARITY 1 gates with qsoc_ck_icg_pos, low while disabled.
 *          POLARITY 0 gates with qsoc_ck_icg_neg, high while disabled.
 *          test_en opens the gate. With CLOCK_DURING_RESET, rst_n sampled
 *          on clk also opens it, from the second rising edge of clk after
 *          reset assertion to the second after release. The enable changes
 *          only on clk edges and reaches clk_out through the gate latch.
 */
module qsoc_clk_gate #(
    parameter CLOCK_DURING_RESET = 1'b0,
    parameter POLARITY = 1'b1
)(
    input  wire clk,        /**< Clock input */
    input  wire en,         /**< Clock enable */
    input  wire test_en,    /**< Test enable */
    /* verilator lint_off UNUSEDSIGNAL */
    input  wire rst_n,      /**< Reset (active low), used with CLOCK_DURING_RESET */
    /* verilator lint_on UNUSEDSIGNAL */
    output wire clk_out     /**< Clock output */
);
    wire reset_open;

    generate
        if (CLOCK_DURING_RESET) begin : g_reset_open
            qsoc_sync #(
                .STAGES(2),
                .RESET_VALUE(1'b0)
            ) u_reset_sync (
                .clk  (clk),
                .rst_n(1'b1),
                .d    (~rst_n),
                .q    (reset_open)
            );
        end else begin : g_reset_closed
            assign reset_open = 1'b0;
        end

        if (POLARITY == 1'b1) begin : g_pos
            qsoc_ck_icg_pos u_icg (
                .clk    (clk),
                .en     (en | reset_open),
                .test_en(test_en),
                .clk_out(clk_out)
            );
        end else begin : g_neg
            qsoc_ck_icg_neg u_icg (
                .clk    (clk),
                .en     (en | reset_open),
                .test_en(test_en),
                .clk_out(clk_out)
            );
        end
    endgenerate
endmodule


/**
 * @brief Configurable clock divider cell module
 *
 * @details Professional implementation matching clk_int_div interface with glitch-free operation.
 *          Supports both odd and even division with 50% duty cycle output.
 */
module qsoc_clk_div #(
    parameter integer WIDTH = 4,           /**< Division value width */
    parameter integer DEFAULT_VAL = 0,     /**< Default divider value after reset */
    parameter CLOCK_DURING_RESET = 1'b0,         /**< Enable clock during reset */
    parameter AUTO_UPDATE = 1'b0                 /**< Load div on change, ignore div_valid */
)(
    input  wire                clk,        /**< Clock input */
    input  wire                rst_n,      /**< Reset (active low) */
    input  wire                en,         /**< Enable */
    input  wire                test_en,    /**< Test mode enable */
    input  wire [WIDTH-1:0]    div,        /**< Division value */
    input  wire                div_valid,  /**< Division value valid */
    output reg                 div_ready,  /**< Division loaded */
    output wire                clk_out,    /**< Clock output */
    output wire [WIDTH-1:0]    count       /**< Cycle counter */
);

    /* Parameter validation - equivalent to $clog2 check for Verilog 2005 */
    function integer clog2;
        input integer value;
        begin
            clog2 = 0;
            while ((1 << clog2) < value) begin
                clog2 = clog2 + 1;
            end
        end
    endfunction
    
    initial begin
        if (clog2(DEFAULT_VAL + 1) > WIDTH) begin
            $display("ERROR: Default divider value %0d is not representable with the configured div value width of %0d bits.", DEFAULT_VAL, WIDTH);
            $finish;
        end
    end

    /* Reset value calculation */
    localparam [WIDTH-1:0] div_reset_value =
        (DEFAULT_VAL != 0) ? DEFAULT_VAL : {{(WIDTH-1){1'b0}}, 1'b1};
    
    /* State registers */
    reg [WIDTH-1:0] div_d, div_q;
    reg toggle_ffs_en;
    reg t_ff1_q;
    reg t_ff1_en;
    reg t_ff2_q;
    reg t_ff2_en;
    reg [WIDTH-1:0] cycle_cntr_d, cycle_cntr_q;
    reg cycle_counter_en;
    reg clk_div_bypass_en_d, clk_div_bypass_en_q;
    reg use_odd_division_d, use_odd_division_q;
    reg gate_en_d, gate_en_q;
    reg gate_is_open_q;
    reg clear_cycle_counter;
    reg [1:0] clk_gate_state_d, clk_gate_state_q;

    /* rst_n sampled on clk: every flop enters and leaves reset on the second
     * rising edge of clk after rst_n moves, so no clock or gate enable changes
     * between clk edges. Reset needs clk running. */
    wire rst_q_n;

    qsoc_sync #(
        .STAGES(2),
        .RESET_VALUE(1'b0)
    ) u_reset_sync (
        .clk  (clk),
        .rst_n(1'b1),
        .d    (rst_n),
        .q    (rst_q_n)
    );

    /* FSM state encoding */
    parameter [1:0] IDLE = 2'b00;
    parameter [1:0] LOAD_DIV = 2'b01;
    parameter [1:0] WAIT_END_PERIOD = 2'b10;

    /* Internal signals */
    wire [WIDTH-1:0] div_i_normalized;
    wire odd_clk;
    wire even_clk;
    wire generated_clock;
    wire ungated_output_clock;
    
    localparam use_odd_division_reset_value = DEFAULT_VAL[0];
    localparam clk_div_bypass_en_reset_value = (DEFAULT_VAL < 2) ? 1'b1 : 1'b0;

    /* Load request: div_valid, or a filtered div that differs from div_q.
     * AUTO_UPDATE synchronizes each bit of div with qsoc_sync and accepts the
     * synchronized value once it holds for two cycles, so a code seen while
     * bits resolve on different cycles is never loaded. The request is a
     * level, so a change arriving while a load is in progress is taken once
     * the divider returns to IDLE. */
    wire [WIDTH-1:0] div_src;
    wire             load_req;
    genvar           div_bit;

    generate
        if (AUTO_UPDATE) begin : g_auto
            wire [WIDTH-1:0] div_sync;
            reg  [WIDTH-1:0] div_last, div_stable;
            reg              load_req_q;
            wire [WIDTH-1:0] div_stable_normalized =
                (div_stable != {WIDTH{1'b0}}) ? div_stable : {{(WIDTH-1){1'b0}}, 1'b1};

            for (div_bit = 0; div_bit < WIDTH; div_bit = div_bit + 1) begin : g_sync
                qsoc_sync #(
                    .STAGES(2),
                    .RESET_VALUE(div_reset_value[div_bit])
                ) u_div_sync (
                    .clk  (clk),
                    .rst_n(rst_q_n),
                    .d    (div[div_bit]),
                    .q    (div_sync[div_bit])
                );
            end

            always @(posedge clk or negedge rst_q_n) begin
                if (!rst_q_n) begin
                    div_last   <= div_reset_value;
                    div_stable <= div_reset_value;
                    load_req_q <= 1'b0;
                end else begin
                    div_last   <= div_sync;
                    if (div_sync == div_last) div_stable <= div_sync;
                    load_req_q <= (div_stable_normalized != div_q);
                end
            end

            assign div_src  = div_stable;
            assign load_req = load_req_q;
        end else begin : g_explicit
            assign div_src  = div;
            assign load_req = div_valid;
        end
    endgenerate

    /* Normalize div input - avoid div=0 issues */
    assign div_i_normalized = (div_src != {WIDTH{1'b0}}) ? div_src : {{(WIDTH-1){1'b0}}, 1'b1};

    /* Divider Load FSM */
    always @(*) begin
        div_d = div_q;
        div_ready = 1'b0;
        clk_div_bypass_en_d = clk_div_bypass_en_q;
        use_odd_division_d = use_odd_division_q;
        clk_gate_state_d = clk_gate_state_q;
        cycle_counter_en = 1'b1;
        clear_cycle_counter = 1'b0;
        toggle_ffs_en = 1'b1;
        gate_en_d = 1'b0;

        case (clk_gate_state_q)
            IDLE: begin
                gate_en_d = 1'b1;
                toggle_ffs_en = 1'b1;
                if (load_req) begin
                    if (div_i_normalized == div_q) begin
                        div_ready = 1'b1;
                    end else begin
                        clk_gate_state_d = LOAD_DIV;
                        gate_en_d = 1'b0;
                    end
                end else if (!en && gate_is_open_q == 1'b0) begin
                    cycle_counter_en = 1'b0;
                    toggle_ffs_en = 1'b0;
                end
            end

            LOAD_DIV: begin
                gate_en_d = 1'b0;
                toggle_ffs_en = 1'b1;
                if ((gate_is_open_q == 1'b0) || clk_div_bypass_en_q) begin
                    toggle_ffs_en = 1'b0;
                    div_d = div_i_normalized;
                    div_ready = 1'b1;
                    clear_cycle_counter = 1'b1;
                    use_odd_division_d = div_i_normalized[0];
                    clk_div_bypass_en_d = (div_i_normalized == {{(WIDTH-1){1'b0}}, 1'b1});
                    clk_gate_state_d = WAIT_END_PERIOD;
                end
            end

            WAIT_END_PERIOD: begin
                gate_en_d = 1'b0;
                toggle_ffs_en = 1'b0;
                if (cycle_cntr_q == (div_q - 1'b1)) begin
                    clk_gate_state_d = IDLE;
                end
            end

            default: begin
                clk_gate_state_d = IDLE;
            end
        endcase
    end

    /* State registers */
    always @(posedge clk or negedge rst_q_n) begin
        if (!rst_q_n) begin
            use_odd_division_q <= use_odd_division_reset_value;
            clk_div_bypass_en_q <= clk_div_bypass_en_reset_value;
            div_q <= div_reset_value;
            clk_gate_state_q <= IDLE;
            gate_en_q <= CLOCK_DURING_RESET;
        end else begin
            use_odd_division_q <= use_odd_division_d;
            clk_div_bypass_en_q <= clk_div_bypass_en_d;
            div_q <= div_d;
            clk_gate_state_q <= clk_gate_state_d;
            gate_en_q <= gate_en_d;
        end
    end

    /* Cycle Counter */
    always @(*) begin
        cycle_cntr_d = cycle_cntr_q;
        if (clear_cycle_counter) begin
            cycle_cntr_d = {WIDTH{1'b0}};
        end else begin
            if (cycle_counter_en) begin
                if (clk_div_bypass_en_q || (cycle_cntr_q == (div_q - 1'b1))) begin
                    cycle_cntr_d = {WIDTH{1'b0}};
                end else begin
                    cycle_cntr_d = cycle_cntr_q + 1'b1;
                end
            end
        end
    end

    always @(posedge clk or negedge rst_q_n) begin
        if (!rst_q_n) begin
            cycle_cntr_q <= {WIDTH{1'b0}};
        end else begin
            cycle_cntr_q <= cycle_cntr_d;
        end
    end

    assign count = cycle_cntr_q;

    /* Precompute (div_q + 1)/2 in WIDTH+1 domain, then truncate to WIDTH.
     * Do this via named wires to avoid part-select on expressions (slang limitation). */
    wire [WIDTH:0]   div_ext            = {1'b0, div_q};
    wire [WIDTH:0]   div_plus1_ext      = div_ext + {{WIDTH{1'b0}}, 1'b1};
    wire [WIDTH:0]   div_plus1_ext_half = div_plus1_ext >> 1;
    wire [WIDTH-1:0] div_plus1_half     = div_plus1_ext_half[WIDTH-1:0];

    /* T-Flip-Flops. Blocking on purpose: t_ff1_q and t_ff2_q are clocks, and a
     * nonblocking update lets flops on those clocks sample data changed by the
     * same clk edge in zero-delay simulation. */
    always @(posedge clk or negedge rst_q_n) begin
        if (!rst_q_n) begin
            t_ff1_q = 1'b0;
        end else if (t_ff1_en) begin
            t_ff1_q = !t_ff1_q;
        end
    end

    always @(negedge clk or negedge rst_q_n) begin
        if (!rst_q_n) begin
            t_ff2_q = 1'b0;
        end else if (t_ff2_en) begin
)v",
    R"v(            t_ff2_q = !t_ff2_q;
        end
    end

    /* T-FF enable control */
    always @(*) begin
        t_ff1_en = 1'b0;
        t_ff2_en = 1'b0;
        if (!clk_div_bypass_en_q && toggle_ffs_en) begin
            if (use_odd_division_q) begin
                t_ff1_en = (cycle_cntr_q == {WIDTH{1'b0}}) ? 1'b1 : 1'b0;
                t_ff2_en = (cycle_cntr_q == div_plus1_half) ? 1'b1 : 1'b0;
            end else begin
                t_ff1_en = ((cycle_cntr_q == {WIDTH{1'b0}}) || (cycle_cntr_q == (div_q >> 1))) ? 1'b1 : 1'b0;
            end
        end
    end

    assign even_clk = t_ff1_q;

    /* Clock XOR for odd division logic */
    qsoc_ck_xor2 i_odd_clk_xor (
        .clk_in0(t_ff1_q),
        .clk_in1(t_ff2_q),
        .clk_out(odd_clk)
    );

    /* Clock MUX to select between odd and even division logic */
    qsoc_ck_mux2 i_clk_mux (
        .clk_in0(even_clk),
        .clk_in1(odd_clk),
        .clk_sel(use_odd_division_q),
        .clk_out(generated_clock)
    );

    /* Clock MUX to bypass clock if divide-by-1 */
    qsoc_ck_mux2 i_clk_bypass_mux (
        .clk_in0(generated_clock),
        .clk_in1(clk),
        .clk_sel(clk_div_bypass_en_q || test_en),
        .clk_out(ungated_output_clock)
    );

    /* With CLOCK_DURING_RESET the gate stays open while in reset */
    wire reset_open = CLOCK_DURING_RESET & ~rst_q_n;

    /* Clock gate feedback signal */
    always @(posedge ungated_output_clock or negedge rst_q_n) begin
        if (!rst_q_n) begin
            gate_is_open_q <= CLOCK_DURING_RESET;
        end else begin
            gate_is_open_q <= gate_en_q & en;
        end
    end

    /* Final clock gate for glitch protection */
    qsoc_clk_gate #(
        .CLOCK_DURING_RESET(1'b0)
    ) i_clk_gate (
        .clk(ungated_output_clock),
        .en((gate_en_q & en) | reset_open),
        .test_en(test_en),
        .rst_n(rst_q_n),
        .clk_out(clk_out)
    );

endmodule


/**
 * @brief Clock OR tree cell module
 *
 * @details Generates an N-input clock OR tree using binary tree of qsoc_ck_or2 instances.
 *          This module recursively builds a balanced tree structure to minimize propagation delay.
 */
module qsoc_clk_or_tree #(
    parameter integer INPUT_COUNT = 4    /**< Number of clock inputs (must be >= 1) */
)(
    input  wire [INPUT_COUNT-1:0] clk_in,  /**< Clock inputs */
    output wire                   clk_out  /**< Clock output */
);
    
    /* Generate recursive binary tree structure */
    generate
        if (INPUT_COUNT < 1) begin : gen_error
            /* Elaboration fails when INPUT_COUNT is below 1 */
            qsoc_param_error_input_count_below_one u_error ();
        end else if (INPUT_COUNT == 1) begin : gen_leaf_single
            /* Single input - direct connection */
            assign clk_out = clk_in[0];
        end else if (INPUT_COUNT == 2) begin : gen_leaf_dual
            /* Two inputs - single OR2 cell */
            qsoc_ck_or2 i_clkor2 (
                .clk_in0(clk_in[0]),
                .clk_in1(clk_in[1]),
                .clk_out(clk_out)
            );
        end else begin : gen_recursive
            /* More than 2 inputs - build recursive tree */
            wire branch_a;  /**< Output from first branch */
            wire branch_b;  /**< Output from second branch */
            
            /* First branch handles lower half of inputs */
            qsoc_clk_or_tree #(
                .INPUT_COUNT(INPUT_COUNT/2)
            ) i_or_branch_a (
                .clk_in(clk_in[0+:INPUT_COUNT/2]),
                .clk_out(branch_a)
            );
            
            /* Second branch handles upper half plus any odd input */
            qsoc_clk_or_tree #(
                .INPUT_COUNT(INPUT_COUNT/2 + INPUT_COUNT%2)
            ) i_or_branch_b (
                .clk_in(clk_in[INPUT_COUNT-1:INPUT_COUNT/2]),
                .clk_out(branch_b)
            );
            
            /* Combine branches with final OR2 cell */
            qsoc_ck_or2 i_clkor2_final (
                .clk_in0(branch_a),
                .clk_in1(branch_b),
                .clk_out(clk_out)
            );
        end
    endgenerate
    
endmodule

/**
 * @brief Glitch-free clock multiplexer cell module
 *
 * @details Template implementation of glitch-free N-input clock multiplexer
 *          based on ETH Zurich common_cells library design.
 *          Supports multi-input with parametrized sync stages and DFT.
 */
module qsoc_clk_mux_gf #(
    parameter integer NUM_INPUTS = 2,        /**< Number of clock inputs */
    parameter integer NUM_SYNC_STAGES = 2,   /**< Synchronizer stages */
    parameter CLOCK_DURING_RESET = 1'b1,     /**< Clock during reset */
    parameter [5:0] WIDTH =                  /**< Helper: select signal width */
        (NUM_INPUTS <= 2)    ? 6'h01 :
        (NUM_INPUTS <= 4)    ? 6'h02 :
        (NUM_INPUTS <= 8)    ? 6'h03 :
        (NUM_INPUTS <= 16)   ? 6'h04 :
        (NUM_INPUTS <= 32)   ? 6'h05 :
        (NUM_INPUTS <= 64)   ? 6'h06 :
        (NUM_INPUTS <= 128)  ? 6'h07 :
        (NUM_INPUTS <= 256)  ? 6'h08 :
        (NUM_INPUTS <= 512)  ? 6'h09 :
        (NUM_INPUTS <= 1024) ? 6'h0A :
        (NUM_INPUTS <= 2048) ? 6'h0B :
        (NUM_INPUTS <= 4096) ? 6'h0C : 6'h20
) (
    input  wire [NUM_INPUTS-1:0] clk_in,        /**< Clock inputs */
    input  wire                  test_clk,      /**< DFT test clock */
    input  wire                  test_en,       /**< DFT test enable */
    input  wire                  async_rst_n,   /**< Async reset (active low) */
    input  wire [WIDTH-1:0]      async_sel,     /**< Async select signal */
    output wire                  clk_out        /**< Clock output */
);
    /* Template implementation - replace with foundry-specific IP */
    
    // Note: NUM_INPUTS must be >= 2 for proper operation
    
    /* Integer alias to avoid signed/unsigned compare warnings */
    localparam integer NUM_INPUTS_I = NUM_INPUTS;
    
    /* Vector-form upper bound for async_sel (same width as async_sel) */
    localparam [WIDTH-1:0] NUM_INPUTS_M1 = NUM_INPUTS_I - 1;
    
    /* Elaboration fails when NUM_INPUTS is below 1. */
    generate
        if (NUM_INPUTS < 1) begin : g_bad_num_inputs
            qsoc_param_error_num_inputs_below_one u_error ();
        end
    endgenerate

    /* Elaboration fails when NUM_SYNC_STAGES is below 1. */
    generate
        if (NUM_SYNC_STAGES < 1) begin : g_bad_num_sync_stages
            qsoc_param_error_num_sync_stages_below_one u_error ();
        end
    endgenerate

    // Internal signals for glitch-free switching
    reg [NUM_INPUTS-1:0]        sel_onehot;
    wire [NUM_INPUTS*2-1:0]   glitch_filter_d;
    reg [NUM_INPUTS*2-1:0]   glitch_filter_q;
    wire [NUM_INPUTS-1:0]        gate_enable_unfiltered;
    wire [NUM_INPUTS-1:0]        glitch_filter_output;
    wire [NUM_INPUTS-1:0]        gate_enable_sync;
    wire [NUM_INPUTS-1:0]        gate_enable;
    reg [NUM_INPUTS-1:0]        clock_disabled_q;
    wire [NUM_INPUTS-1:0]        gated_clock;
    wire                         output_clock;
    wire [NUM_INPUTS-1:0]        reset_synced;
    
    /* Onehot decoder */
    always @(*) begin
        sel_onehot = {NUM_INPUTS{1'b0}};
        /* compare vector vs vector to avoid sign-compare warning */
        if (async_sel <= NUM_INPUTS_M1)
            sel_onehot[async_sel] = 1'b1;
    end
    
    // Generate logic for each input clock
    genvar i;
    generate
    for (i = 0; i < NUM_INPUTS_I; i = i + 1) begin : gen_input_stages
        /* Reset released on the second rising edge of clk_in[i] */
        qsoc_sync #(
            .STAGES(2),
            .RESET_VALUE(1'b0)
        ) u_reset_sync (
            .clk  (clk_in[i]),
            .rst_n(async_rst_n),
            .d    (1'b1),
            .q    (reset_synced[i])
        );
        
        /* Gate enable generation with mutual exclusion */
        /* Generate one-hot mask for current input i (compile-time constant) */
        localparam [NUM_INPUTS_I-1:0] ONEHOT_I = ({{(NUM_INPUTS_I-1){1'b0}},1'b1} << i);
        
        /* Set bit i to 1 to exclude it from constraint, then use reduction AND */
        assign gate_enable_unfiltered[i] = sel_onehot[i] & &(clock_disabled_q | ONEHOT_I);
        
        // Glitch filter (2-stage)
        assign glitch_filter_d[i*2+0] = gate_enable_unfiltered[i];
        assign glitch_filter_d[i*2+1] = glitch_filter_q[i*2+0];
        
        always @(posedge clk_in[i] or negedge reset_synced[i]) begin
            if (!reset_synced[i]) begin
                glitch_filter_q[i*2+1:i*2] <= 2'b00;
            end else begin
                glitch_filter_q[i*2+1:i*2] <= glitch_filter_d[i*2+1:i*2];
            end
        end
        
        assign glitch_filter_output[i] = glitch_filter_q[i*2+1] &
                                         glitch_filter_q[i*2+0] &
                                         gate_enable_unfiltered[i];
        
        /* Enable synchronized into the clk_in[i] domain. It has no reset: the
         * filter is held in reset, so the chain empties on clk_in[i] edges and
         * the gate enable only changes on those edges. */
        qsoc_sync #(
            .STAGES(NUM_SYNC_STAGES),
            .RESET_VALUE(1'b0)
        ) u_enable_sync (
            .clk  (clk_in[i]),
            .rst_n(1'b1),
            .d    (glitch_filter_output[i]),
            .q    (gate_enable_sync[i])
        );
        
        /* With CLOCK_DURING_RESET the selected input is enabled while in reset,
         * from reset and select both sampled on clk_in[i] */
        if (CLOCK_DURING_RESET) begin : gen_reset_open
            wire reset_hold;
            wire sel_sync;
            qsoc_sync #(
                .STAGES(2),
                .RESET_VALUE(1'b0)
            ) u_reset_hold (
                .clk  (clk_in[i]),
                .rst_n(1'b1),
                .d    (~async_rst_n),
                .q    (reset_hold)
            );
            qsoc_sync #(
                .STAGES(2),
                .RESET_VALUE(1'b0)
            ) u_sel_sync (
                .clk  (clk_in[i]),
                .rst_n(1'b1),
                .d    (sel_onehot[i]),
                .q    (sel_sync)
            );
            assign gate_enable[i] = gate_enable_sync[i] | (reset_hold & sel_sync);
        end else begin : gen_reset_closed
            assign gate_enable[i] = gate_enable_sync[i];
        end
        
        qsoc_ck_icg_pos u_icg (
            .clk    (clk_in[i]),
            .en     (gate_enable[i]),
            .test_en(1'b0),
            .clk_out(gated_clock[i])
        );
        
        // Feedback for mutual exclusion
        always @(posedge clk_in[i] or negedge reset_synced[i]) begin
            if (!reset_synced[i]) begin
                clock_disabled_q[i] <= 1'b1;
            end else begin
                clock_disabled_q[i] <= ~gate_enable[i];
            end
        end
    end
    endgenerate
    
    // Output OR gate using dedicated clock OR tree
    qsoc_clk_or_tree #(
        .INPUT_COUNT(NUM_INPUTS)
    ) i_clk_or_tree (
        .clk_in(gated_clock),
        .clk_out(output_clock)
    );
    
    // DFT mux: select between functional clock and test clock using dedicated clock mux
    qsoc_ck_mux2 i_test_clk_mux (
        .clk_in0(output_clock),
        .clk_in1(test_clk),
        .clk_sel(test_en),
        .clk_out(clk_out)
    );
    
endmodule

/**
 * @brief Standard (non-glitch-free) clock multiplexer cell module
 *
 * @details Template implementation of simple N-input clock multiplexer
 *          using pure combinational logic. No glitch protection.
 */
module qsoc_clk_mux_raw #(
    parameter integer NUM_INPUTS = 2,
    parameter [5:0] WIDTH =                  /**< Helper: select signal width */
        (NUM_INPUTS <= 2)    ? 6'h01 :
        (NUM_INPUTS <= 4)    ? 6'h02 :
        (NUM_INPUTS <= 8)    ? 6'h03 :
        (NUM_INPUTS <= 16)   ? 6'h04 :
        (NUM_INPUTS <= 32)   ? 6'h05 :
)v",
    R"v(        (NUM_INPUTS <= 64)   ? 6'h06 :
        (NUM_INPUTS <= 128)  ? 6'h07 :
        (NUM_INPUTS <= 256)  ? 6'h08 :
        (NUM_INPUTS <= 512)  ? 6'h09 :
        (NUM_INPUTS <= 1024) ? 6'h0A :
        (NUM_INPUTS <= 2048) ? 6'h0B :
        (NUM_INPUTS <= 4096) ? 6'h0C : 6'h20
) (
    input  wire [NUM_INPUTS-1:0] clk_in,        /**< Clock inputs */
    input  wire [WIDTH-1:0]      clk_sel,       /**< Clock select signal */
    output wire                  clk_out        /**< Clock output */
);
    /* Template implementation - replace with foundry-specific IP */
    
    /* Generate recursive binary tree multiplexer structure */
    generate
        if (NUM_INPUTS < 1) begin : gen_error
            /* Elaboration fails when NUM_INPUTS is below 1 */
            qsoc_param_error_num_inputs_below_one u_error ();
        end else if (NUM_INPUTS == 1) begin : gen_leaf_single
            /* Single input - direct connection */
            assign clk_out = clk_in[0];
        end else if (NUM_INPUTS == 2) begin : gen_leaf_dual
            /* Two inputs - single MUX2 cell */
            qsoc_ck_mux2 i_clkmux2 (
                .clk_in0(clk_in[0]),
                .clk_in1(clk_in[1]),
                .clk_sel(clk_sel[0]),
                .clk_out(clk_out)
            );
        end else begin : gen_recursive
            /* More than 2 inputs - build recursive tree */
            wire branch_a;      /**< Output from first branch */
            wire branch_b;      /**< Output from second branch */
            
            /* Use MSB to select between two halves, remaining bits for sub-selection */
            wire msb_sel;       /**< MSB selects between upper and lower half */
            wire [WIDTH-2:0] lower_sel;  /**< Lower bits for sub-mux selection */
            
            assign msb_sel = clk_sel[WIDTH-1];
            assign lower_sel = clk_sel[WIDTH-2:0];
            
            /* The MSB splits the inputs at a power of two */
            localparam integer HALF = 1 << (WIDTH - 1);
            /* Select width of the second branch, as its WIDTH default computes */
            localparam integer REST_WIDTH =
                (NUM_INPUTS - HALF <= 2) ? 1 : (NUM_INPUTS - HALF <= 4) ? 2 :
                (NUM_INPUTS - HALF <= 8) ? 3 : (NUM_INPUTS - HALF <= 16) ? 4 :
                (NUM_INPUTS - HALF <= 32) ? 5 : (NUM_INPUTS - HALF <= 64) ? 6 :
                (NUM_INPUTS - HALF <= 128) ? 7 : (NUM_INPUTS - HALF <= 256) ? 8 :
                (NUM_INPUTS - HALF <= 512) ? 9 : (NUM_INPUTS - HALF <= 1024) ? 10 :
                (NUM_INPUTS - HALF <= 2048) ? 11 : 12;
            
            /* First branch handles the HALF inputs with MSB clear */
            qsoc_clk_mux_raw #(
                .NUM_INPUTS(HALF)
            ) i_mux_branch_a (
                .clk_in(clk_in[0+:HALF]),
                .clk_sel(lower_sel),
                .clk_out(branch_a)
            );
            
            /* Second branch handles the rest, with MSB set */
            qsoc_clk_mux_raw #(
                .NUM_INPUTS(NUM_INPUTS - HALF)
            ) i_mux_branch_b (
                .clk_in(clk_in[NUM_INPUTS-1:HALF]),
                .clk_sel(lower_sel[REST_WIDTH-1:0]),
                .clk_out(branch_b)
            );
            
            /* Combine branches with final MUX2 cell using MSB */
            qsoc_ck_mux2 i_clkmux2_final (
                .clk_in0(branch_a),
                .clk_in1(branch_b),
                .clk_sel(msb_sel),
                .clk_out(clk_out)
            );
        end
    endgenerate
    
endmodule
)v",
};

const char *const resetCell[] = {
    R"v(/**
 * @file qsoc_cell_reset.v
 * @brief Template reset cells for QSoC reset primitives
 *
 * @details This file contains template reset cell modules for reset primitives.
 *          Auto-generated template file. Generated by qsoc.
 * CAUTION: Please replace the templates in this file
 *          with your technology's standard-cell implementations
 *          before using in production.
 */

`timescale 1ns / 1ps
/**
 * @brief Asynchronous reset synchronizer (active-low)
 * @param STAGE Number of sync stages (>=2 recommended)
 */
module qsoc_rst_sync
#(
    parameter integer STAGE = 3
)
(
    input  wire clk,        /**< Clock input */
    input  wire rst_in_n,   /**< Reset input (active-low) */
    input  wire test_enable, /**< Test enable signal */
    output wire rst_out_n   /**< Reset output (active-low) */
);

    /* Elaboration fails when STAGE is below 1. */
    generate
        if (STAGE < 1) begin : g_bad_stage
            qsoc_param_error_stage_below_one u_error ();
        end
    endgenerate

    wire core_rst_n;

    qsoc_sync #(
        .STAGES(STAGE),
        .RESET_VALUE(1'b0)
    ) u_sync (
        .clk  (clk),
        .rst_n(rst_in_n),
        .d    (1'b1),
        .q    (core_rst_n)
    );

    qsoc_ck_mux2 u_test_mux (
        .clk_in0(core_rst_n),
        .clk_in1(rst_in_n),
        .clk_sel(test_enable),
        .clk_out(rst_out_n)
    );

endmodule

/**
 * @brief Synchronous reset pipeline (active-low)
 * @param STAGE Number of pipeline stages (>=1)
 */
module qsoc_rst_pipe
#(
    parameter integer STAGE = 4
)
(
    input  wire clk,        /**< Clock input */
    input  wire rst_in_n,   /**< Reset input (active-low) */
    input  wire test_enable, /**< Test enable signal */
    output wire rst_out_n   /**< Reset output (active-low) */
);

    /* Elaboration fails when STAGE is below 1. */
    generate
        if (STAGE < 1) begin : g_bad_stage
            qsoc_param_error_stage_below_one u_error ();
        end
    endgenerate

    reg  [STAGE-1:0] pipe_reg;
    wire         core_rst_n;

    generate
        if (STAGE == 1) begin : g_st1
            always @(posedge clk) begin
                if (!rst_in_n) pipe_reg <= 1'b0;
                else           pipe_reg <= 1'b1;
            end
        end else begin : g_stN
            always @(posedge clk) begin
                if (!rst_in_n) pipe_reg <= {STAGE{1'b0}};
                else           pipe_reg <= {pipe_reg[STAGE-2:0], 1'b1};
            end
        end
    endgenerate

    assign core_rst_n = pipe_reg[STAGE-1];
    qsoc_ck_mux2 u_test_mux (
        .clk_in0(core_rst_n),
        .clk_in1(rst_in_n),
        .clk_sel(test_enable),
        .clk_out(rst_out_n)
    );

endmodule

/**
 * @brief Counter-based reset release (active-low)
 * @param CYCLE Rising edges of clk from release of rst_in_n to release of
 *              rst_out_n, at least 2. The first two pass a qsoc_sync.
 */
module qsoc_rst_count
#(
    parameter integer CYCLE = 16
)
(
    input  wire clk,        /**< Clock input */
    input  wire rst_in_n,   /**< Reset input (active-low) */
    input  wire test_enable, /**< Test enable signal */
    output wire rst_out_n   /**< Reset output (active-low) */
);

    /* ceil(log2(n)) for n>=1 */
    function integer clog2;
        input integer n;
        integer v;
        begin
            v = (n < 1) ? 1 : n - 1;
            clog2 = 0;
            while (v > 0) begin
                v = v >> 1;
                clog2 = clog2 + 1;
            end
            if (clog2 == 0) clog2 = 1;
        end
    endfunction

    /* Elaboration fails when CYCLE is below 1. */
    generate
        if (CYCLE < 1) begin : g_bad_cycle
            qsoc_param_error_cycle_below_one u_error ();
        end
    endgenerate

    /* Release synchronized to clk, then CYCLE - 2 more rising edges */
    wire sync_rst_n;
    wire core_rst_n;

    qsoc_sync #(
        .STAGES(2),
        .RESET_VALUE(1'b0)
    ) u_sync (
        .clk  (clk),
        .rst_n(rst_in_n),
        .d    (1'b1),
        .q    (sync_rst_n)
    );

    generate
        if (CYCLE <= 2) begin : g_sync_only
            assign core_rst_n = sync_rst_n;
        end else begin : g_count
            localparam integer CNT_WIDTH = clog2(CYCLE - 2);
            localparam [CNT_WIDTH-1:0] C_M1 = CYCLE - 3;

            reg [CNT_WIDTH-1:0] cnt;
            reg                 count_rst_n;

            always @(posedge clk or negedge sync_rst_n) begin
                if (!sync_rst_n) begin
                    cnt         <= {CNT_WIDTH{1'b0}};
                    count_rst_n <= 1'b0;
                end else if (!count_rst_n) begin
                    if (cnt == C_M1) begin
                        count_rst_n <= 1'b1;
                    end else begin
                        cnt <= cnt + {{(CNT_WIDTH-1){1'b0}}, 1'b1};
                    end
                end
            end

            assign core_rst_n = count_rst_n;
        end
    endgenerate

    qsoc_ck_mux2 u_test_mux (
        .clk_in0(core_rst_n),
        .clk_in1(rst_in_n),
        .clk_sel(test_enable),
        .clk_out(rst_out_n)
    );

endmodule

)v",
};

const char *const powerCell[] = {
    R"v(`timescale 1ns / 1ps

/* qsoc_cell_power.v
 * Module: qsoc_power_fsm
 * Minimal per-domain power controller with strict power sequencing
 * Power-up   : enable switch -> wait pgood+settle -> clock on -> release reset
 * Power-down : assert reset -> clock off and disable switch -> wait drop+settle
 * Hard depend blocks on timeout and enters FAULT with auto-heal
 * Soft depend warns on timeout and proceeds
 * pgood, ctrl_enable and fault_clear pass through qsoc_sync; dep_hard_all and
 * dep_soft_all come from FSMs on the same clock
 * Outputs are flops loaded from the decode of the next state
 * rst_n asserts at once and releases through qsoc_sync
 * fault_clear clears fault in any state; a new fault on the same edge wins
 * test_en=1 forces power on, clock on, reset released, while FSM state is preserved
 */

module qsoc_power_fsm
#(
    /* Parameters appear before ports as required by Verilog-2005. */
    parameter integer HAS_SWITCH        = 1,   /**< 1=drive switch              */
    parameter integer WAIT_DEP_CYCLES   = 100, /**< depend wait window (cycles) */
    parameter integer SETTLE_ON_CYCLES  = 100, /**< power-on settle (cycles)    */
    parameter integer SETTLE_OFF_CYCLES = 50   /**< power-off settle cycles     */
)
(
    /* AO host clock/reset only */
    input  wire clk,              /**< AO host clock                        */
    input  wire rst_n,            /**< AO host reset, active-low            */

    /* Control and monitors */
    input  wire test_en,          /**< DFT enable to force on               */
    input  wire ctrl_enable,      /**< target state: 1=on, 0=off            */
    input  wire fault_clear,      /**< pulse to clear sticky fault          */

    input  wire dep_hard_all,     /**< AND of all hard-depend ready inputs  */
    input  wire dep_soft_all,     /**< AND of all soft-depend ready inputs  */
    input  wire pgood,            /**< power good of this domain            */

    /* Domain-side controls */
    output wire clk_enable,       /**< ICG enable for this domain clock     */
    output wire rst_gate_n,       /**< reset gate to synchronizer, active-low */
    output wire pwr_switch,       /**< power switch control                 */

    /* Status */
    output wire ready,            /**< domain usable clock on reset off     */
    output wire valid,            /**< voltage stable                       */
    output reg  fault             /**< sticky fault indicator               */
);

    /** Return number of bits to hold value n at least 1 */
    function integer bits_for;
        input integer n;
        integer val, nbits;
    begin
        val = (n < 1) ? 1 : n;
        val = val - 1;
        nbits = 0;
        while (val > 0) begin
            nbits = nbits + 1;
            val = val >> 1;
        end
        if (nbits < 1) nbits = 1;
        bits_for = nbits;
    end
    endfunction

    localparam integer MAX_ONOFF =
        (SETTLE_ON_CYCLES > SETTLE_OFF_CYCLES) ? SETTLE_ON_CYCLES : SETTLE_OFF_CYCLES;
    localparam integer MAX_ALL =
        (MAX_ONOFF > WAIT_DEP_CYCLES) ? MAX_ONOFF : WAIT_DEP_CYCLES;
    localparam integer WIDTH = bits_for(MAX_ALL);

    /* add two light-weight states for strict ordering */
    localparam [2:0] S_OFF        = 3'd0;
    localparam [2:0] S_WAIT_DEP   = 3'd1;
    localparam [2:0] S_TURN_ON    = 3'd2;
    localparam [2:0] S_ON         = 3'd3;
    localparam [2:0] S_TURN_OFF   = 3'd4;
    localparam [2:0] S_FAULT      = 3'd5;
    localparam [2:0] S_CLK_ON     = 3'd6;  /**< clock on, reset held        */
    localparam [2:0] S_RST_ASSERT = 3'd7;  /**< reset asserted, clock on    */

    reg [2:0] state, state_n;

    /* rst_n asserts at once and releases on the second rising edge of clk */
    wire rst_q_n;

    qsoc_sync #(
        .STAGES(2),
        .RESET_VALUE(1'b0)
    ) u_reset_sync (
        .clk  (clk),
        .rst_n(rst_n),
        .d    (1'b1),
        .q    (rst_q_n)
    );

    /* Inputs from other clock domains */
    wire ctrl_enable_s, fault_clear_s, pgood_s;

    qsoc_sync #(
        .STAGES(2),
        .RESET_VALUE(1'b0)
    ) u_ctrl_enable_sync (
        .clk  (clk),
        .rst_n(rst_q_n),
        .d    (ctrl_enable),
        .q    (ctrl_enable_s)
    );

    qsoc_sync #(
        .STAGES(2),
        .RESET_VALUE(1'b0)
    ) u_fault_clear_sync (
        .clk  (clk),
        .rst_n(rst_q_n),
        .d    (fault_clear),
        .q    (fault_clear_s)
    );

    qsoc_sync #(
        .STAGES(2),
        .RESET_VALUE(1'b0)
    ) u_pgood_sync (
        .clk  (clk),
        .rst_n(rst_q_n),
        .d    (pgood),
        .q    (pgood_s)
    );

    reg [WIDTH-1:0] t_dep, t_on, t_off;
    reg             ld_dep, dec_dep;
    reg             ld_on,  dec_on;
    reg             ld_off, dec_off;

    /* One-cycle set for soft-timeout fault */
    reg set_fault_soft;

    /* 1) Sequential: state, timers, sticky fault */
    always @(posedge clk or negedge rst_q_n) begin
        if (!rst_q_n) begin
            state <= S_OFF;
            t_dep <= {WIDTH{1'b0}};
            t_on  <= {WIDTH{1'b0}};
            t_off <= {WIDTH{1'b0}};
            fault <= 1'b0;
        end else begin
            state <= state_n;

            /* Load N-1; zero means no wait */
            if (ld_dep)
                t_dep <= (WAIT_DEP_CYCLES == 0) ? {WIDTH{1'b0}}
                                               : WAIT_DEP_CYCLES - 1;
            else if (dec_dep && t_dep != 0)
                t_dep <= t_dep - 1'b1;

            if (ld_on)
                t_on  <= (SETTLE_ON_CYCLES == 0) ? {WIDTH{1'b0}}
                                                : SETTLE_ON_CYCLES - 1;
            else if (dec_on && t_on != 0)
                t_on  <= t_on - 1'b1;

            if (ld_off)
                t_off <= (SETTLE_OFF_CYCLES == 0) ? {WIDTH{1'b0}}
                                                 : SETTLE_OFF_CYCLES - 1;
            else if (dec_off && t_off != 0)
                t_off <= t_off - 1'b1;

            /* Sticky fault: set by a soft timeout or on entering S_FAULT,
             * cleared by fault_clear in any state, set wins */
            if (set_fault_soft || (state_n == S_FAULT && state != S_FAULT)) fault <= 1'b1;
            else if (fault_clear_s) fault <= 1'b0;
        end
    end

    /* 2) Combinational: next state */
    always @* begin
        state_n        = state;
        ld_dep         = 1'b0;  dec_dep  = 1'b0;
        ld_on          = 1'b0;  dec_on   = 1'b0;
        ld_off         = 1'b0;  dec_off  = 1'b0;
        set_fault_soft = 1'b0;

        case (state)
        S_OFF: begin
            if (ctrl_enable_s) begin
                state_n = S_WAIT_DEP;
                ld_dep  = 1'b1;
            end
        end

        S_WAIT_DEP: begin
            if (!ctrl_enable_s) begin
                state_n = S_OFF;
            end else if (dep_hard_all &&
                        (dep_soft_all || (t_dep == 0))) begin
                if (!dep_soft_all && (t_dep == 0))
                    set_fault_soft = 1'b1; /* soft miss -> warn */
                state_n = S_TURN_ON;
                ld_on   = 1'b1;
            end else if (!dep_hard_all && (t_dep == 0)) begin
                state_n = S_FAULT;  /* hard miss -> block */
                ld_dep  = 1'b1;     /* start cooldown */
            end else begin
                dec_dep = 1'b1;
            end
        end

        S_TURN_ON: begin
            /* t_on runs as window until pgood_s rises; once high, it must remain high until t_on==0 */
            if (!ctrl_enable_s) begin
                state_n = S_TURN_OFF;
                ld_off  = 1'b1;
            end else if (pgood_s) begin
                if (t_on == 0) state_n = S_CLK_ON; /* go to clock on state */
                else           dec_on  = 1'b1;     /* settle countdown only when pgood_s */
            end else begin
                if (t_on == 0) begin
                    state_n = S_FAULT; /* on-timeout */
                    ld_dep  = 1'b1;    /* cooldown */
                end else begin
                    dec_on  = 1'b1;    /* timeout countdown when !pgood_s */
                end
            end
        end

        S_ON: begin
            if (!ctrl_enable_s) begin
                state_n = S_RST_ASSERT; /* assert reset first */
            end
        end

        S_TURN_OFF: begin
            if (!pgood_s) begin
                if (t_off == 0) state_n = S_OFF;
                else            dec_off = 1'b1;
            end else begin
                if (t_off == 0) begin
                    state_n = S_FAULT; /* off-timeout */
                    ld_dep  = 1'b1;    /* cooldown */
                end else begin
                    dec_off = 1'b1;
                end
            end
        end

        S_FAULT: begin
            if (!ctrl_enable_s) begin
                state_n = S_OFF;
            end else if (dep_hard_all && (t_dep == 0)) begin
                state_n = S_WAIT_DEP; /* auto-heal after cooldown */
                ld_dep  = 1'b1;
            end else begin
                if (t_dep != 0) dec_dep = 1'b1;
                state_n = S_FAULT;
            end
        end

        /* New states for clock-before-reset sequencing */
        S_CLK_ON: begin
            /* Single cycle to allow clock stabilization before reset release */
            state_n = S_ON;
        end

        S_RST_ASSERT: begin
            /* Assert reset first while clock is still on, then proceed to turn off */
            state_n = S_TURN_OFF;
            ld_off  = 1'b1;
        end

        default: state_n = S_FAULT;
        endcase
    end

    /* 3) Outputs: decode of the next state, registered below */
    reg clk_enable_d, rst_gate_n_d, pwr_switch_d, ready_d, valid_d;

    always @* begin
        clk_enable_d = 1'b0;
        rst_gate_n_d = 1'b0;
        pwr_switch_d = 1'b0;
        ready_d      = 1'b0;
        valid_d      = 1'b0;

        case (state_n)
        S_OFF: begin
            /* Off: clock gated, reset asserted, switch off */
        end
        S_WAIT_DEP: begin
            /* Waiting for dependencies with power off */
        end
        S_TURN_ON: begin
            if (HAS_SWITCH) pwr_switch_d = 1'b1 /* request power */;
            valid_d = pgood_s;
            /* t_on counts as window; transition requires pgood_s==1 when t_on==0 */
        end
        S_ON: begin
            /* Clock stays on, release reset, domain ready */
            if (HAS_SWITCH) pwr_switch_d = 1'b1;
            valid_d     = 1'b1;
            rst_gate_n_d = 1'b1;  /* release reset */
            clk_enable_d= 1'b1;  /* enable clock */
            ready_d     = 1'b1;
        end
        S_TURN_OFF: begin
            /* Reset asserted, clock gated, switch off, waiting for pgood_s drop + settle */
            valid_d = pgood_s;
        end
        /* New states for clock-before-reset sequencing */
        S_CLK_ON: begin
            if (HAS_SWITCH) pwr_switch_d = 1'b1;
            clk_enable_d = 1'b1;
            valid_d = pgood_s;
            rst_gate_n_d = 1'b0;  /* hold reset for one cycle before release */
        end
        S_RST_ASSERT: begin
            if (HAS_SWITCH) pwr_switch_d = 1'b1;
            clk_enable_d = 1'b1;
            valid_d = pgood_s;
            rst_gate_n_d = 1'b0;  /* assert reset before clock disable */
        end
        S_FAULT: begin
            /* Quarantine: clock off, reset asserted, power off */
        end
        endcase
    end

    reg clk_enable_q, rst_gate_n_q, pwr_switch_q, ready_q, valid_q;

    always @(posedge clk or negedge rst_q_n) begin
        if (!rst_q_n) begin
            clk_enable_q <= 1'b0;
            rst_gate_n_q <= 1'b0;
            pwr_switch_q <= 1'b0;
            ready_q      <= 1'b0;
            valid_q      <= 1'b0;
        end else begin
            clk_enable_q <= clk_enable_d;
            rst_gate_n_q <= rst_gate_n_d;
            pwr_switch_q <= pwr_switch_d;
            ready_q      <= ready_d;
)v",
    R"v(            valid_q      <= valid_d;
        end
    end

    /* DFT force-on override, test_en is static */
    assign clk_enable = clk_enable_q | test_en;
    assign rst_gate_n = rst_gate_n_q | test_en;
    assign pwr_switch = pwr_switch_q | (test_en & (HAS_SWITCH != 0));
    assign ready      = ready_q | test_en;
    assign valid      = valid_q | test_en;

endmodule

/* qsoc_power_rst_sync
 * Async assert, sync deassert reset synchronizer for power domains
 * Assert does not require clock, deassert requires STAGE edges on clk_dom
 */
module qsoc_power_rst_sync #(parameter integer STAGE=4)(
    input  wire clk_dom,      /**< domain clock source                   */
    input  wire rst_gate_n,   /**< async assert, sync deassert           */
    input  wire test_en,      /**< DFT force release                     */
    output wire rst_dom_n     /**< synchronized domain reset, active-low */
);
    /* Elaboration fails when STAGE is below 1. */
    generate
        if (STAGE < 1) begin : g_bad_stage
            qsoc_param_error_stage_below_one u_error ();
        end
    endgenerate

    wire sync_n;

    qsoc_sync #(
        .STAGES(STAGE),
        .RESET_VALUE(1'b0)
    ) u_sync (
        .clk  (clk_dom),
        .rst_n(rst_gate_n),
        .d    (1'b1),
        .q    (sync_n)
    );

    /* test_en overrides to release reset */
    qsoc_ck_or2 u_test_or (
        .clk_in0(sync_n),
        .clk_in1(test_en),
        .clk_out(rst_dom_n)
    );
endmodule
)v",
};

template<size_t N>
QString join(const char *const (&parts)[N])
{
    QString text;
    for (const char *part : parts)
        text += QString::fromUtf8(part);
    return text;
}

} // namespace

QString QSocCellText::clock()
{
    return join(clockCell);
}

QString QSocCellText::reset()
{
    return join(resetCell);
}

QString QSocCellText::power()
{
    return join(powerCell);
}
