// SPDX-License-Identifier: Apache-2.0
// SPDX-FileCopyrightText: 2026 Huang Rui <vowstar@gmail.com>

#include "common/qsociomuxformal.h"

#include "common/qsociomuxgenerator.h"

#include <QStringList>

namespace {

quint32 selectorWidth(quint32 hsSlots)
{
    if (hsSlots <= 2) {
        return 1;
    }
    if (hsSlots <= 4) {
        return 2;
    }
    return 3;
}

QString roleKey(QSocIomuxRole role)
{
    switch (role) {
    case QSocIomuxRole::InputValue:
        return QStringLiteral("input_value");
    case QSocIomuxRole::InputEnable:
        return QStringLiteral("input_enable");
    case QSocIomuxRole::OutputValue:
        return QStringLiteral("output_value");
    case QSocIomuxRole::OutputEnable:
        return QStringLiteral("output_enable");
    }
    return QString();
}

QString endpointPortName(quint32 pin, quint32 slot, QSocIomuxRole role)
{
    const QString suffix = role == QSocIomuxRole::InputValue ? QStringLiteral("o")
                                                             : QStringLiteral("i");
    return QString("hs_p%1_s%2_%3_%4").arg(pin).arg(slot).arg(roleKey(role), suffix);
}

const QSocIomuxEndpointPlan &routeRole(const QSocIomuxRoutePlan &route, QSocIomuxRole role)
{
    switch (role) {
    case QSocIomuxRole::InputValue:
        return route.inputValue;
    case QSocIomuxRole::InputEnable:
        return route.inputEnable;
    case QSocIomuxRole::OutputValue:
        return route.outputValue;
    case QSocIomuxRole::OutputEnable:
        break;
    }
    return route.outputEnable;
}

const QSocIomuxRoutePlan *findRoute(const QSocIomuxPlan &plan, quint32 pin, quint32 slot)
{
    for (const QSocIomuxRoutePlan &route : plan.routes) {
        if (route.pin == pin && route.slot == slot) {
            return &route;
        }
    }
    return nullptr;
}

QString expectedRoleExpression(
    const QSocIomuxPlan &plan, quint32 pin, quint32 slot, QSocIomuxRole role)
{
    const QSocIomuxRoutePlan *route = findRoute(plan, pin, slot);
    if (route == nullptr) {
        return QStringLiteral("1'b0");
    }
    const QSocIomuxEndpointPlan &endpoint = routeRole(*route, role);
    if (!endpoint.link.isEmpty()) {
        const QString name = endpointPortName(pin, slot, role);
        return endpoint.invert ? name + " ^ 1'b1" : name;
    }
    if (endpoint.constant.has_value() && *endpoint.constant == 1) {
        return QStringLiteral("1'b1");
    }
    return QStringLiteral("1'b0");
}

QString buildSystemVerilog(const QSocIomuxPlan &plan)
{
    const quint32 width = selectorWidth(plan.hsSlots);
    const quint64 dense = quint64(plan.hsSlots) * plan.pinCount;

    QStringList txPorts;
    QStringList rxPorts;
    for (const QSocIomuxRoutePlan &route : plan.routes) {
        for (const QSocIomuxRole role :
             {QSocIomuxRole::InputValue,
              QSocIomuxRole::InputEnable,
              QSocIomuxRole::OutputValue,
              QSocIomuxRole::OutputEnable}) {
            const QSocIomuxEndpointPlan &endpoint = routeRole(route, role);
            if (endpoint.link.isEmpty()) {
                continue;
            }
            const QString name = endpointPortName(route.pin, route.slot, role);
            if (role == QSocIomuxRole::InputValue) {
                rxPorts.append(name);
            } else {
                txPorts.append(name);
            }
        }
    }

    QStringList lines;
    lines.append("// Generated by QSoC. Do not edit.");
    lines.append(QString("module %1_hs_formal (").arg(plan.moduleName));
    QStringList declarations;
    declarations.append(QString("    input logic [%1:0] pad_input_value_i").arg(plan.pinCount - 1));
    for (quint32 pin = 0; pin < plan.pinCount; ++pin) {
        declarations.append(
            QString("    input logic [%1:0] pin_%2_select_i").arg(width - 1).arg(pin));
    }
    for (const QString &name : txPorts) {
        declarations.append(QString("    input logic %1").arg(name));
    }
    for (qsizetype index = 0; index < declarations.size(); ++index) {
        const QString suffix = index + 1 == declarations.size() ? QString() : QString(",");
        lines.append(declarations.at(index) + suffix);
    }
    lines.append(");");
    lines.append(QString());
    lines.append(QString("logic [%1:0] tx_input_enable_w;").arg(dense - 1));
    lines.append(QString("logic [%1:0] tx_output_value_w;").arg(dense - 1));
    lines.append(QString("logic [%1:0] tx_output_enable_w;").arg(dense - 1));
    lines.append(QString("logic [%1:0] rx_input_value_w;").arg(dense - 1));
    lines.append(QString("logic [%1:0] pad_input_enable_w;").arg(plan.pinCount - 1));
    lines.append(QString("logic [%1:0] pad_output_value_w;").arg(plan.pinCount - 1));
    lines.append(QString("logic [%1:0] pad_output_enable_w;").arg(plan.pinCount - 1));
    for (const QString &name : rxPorts) {
        lines.append(QString("logic %1;").arg(name));
    }
    lines.append(QString());

    QStringList connConnections
        = {"    .tx_input_enable_o(tx_input_enable_w)",
           "    .tx_output_value_o(tx_output_value_w)",
           "    .tx_output_enable_o(tx_output_enable_w)",
           "    .rx_input_value_i(rx_input_value_w)"};
    for (const QSocIomuxRoutePlan &route : plan.routes) {
        for (const QSocIomuxRole role :
             {QSocIomuxRole::InputValue,
              QSocIomuxRole::InputEnable,
              QSocIomuxRole::OutputValue,
              QSocIomuxRole::OutputEnable}) {
            if (routeRole(route, role).link.isEmpty()) {
                continue;
            }
            const QString name = endpointPortName(route.pin, route.slot, role);
            connConnections.append(QString("    .%1(%1)").arg(name));
        }
    }
    lines.append(QString("%1_conn u_conn (").arg(plan.moduleName));
    for (qsizetype index = 0; index < connConnections.size(); ++index) {
        const QString suffix = index + 1 == connConnections.size() ? QString() : QString(",");
        lines.append(connConnections.at(index) + suffix);
    }
    lines.append(");");
    lines.append(QString());

    QStringList coreConnections
        = {"    .pad_input_value_i(pad_input_value_i)",
           "    .pad_input_enable_o(pad_input_enable_w)",
           "    .pad_output_value_o(pad_output_value_w)",
           "    .pad_output_enable_o(pad_output_enable_w)",
           "    .tx_input_enable_i(tx_input_enable_w)",
           "    .tx_output_value_i(tx_output_value_w)",
           "    .tx_output_enable_i(tx_output_enable_w)",
           "    .rx_input_value_o(rx_input_value_w)"};
    for (quint32 pin = 0; pin < plan.pinCount; ++pin) {
        coreConnections.append(QString("    .pin_%1_select_i(pin_%1_select_i)").arg(pin));
    }
    lines.append(QString("%1_core u_core (").arg(plan.moduleName));
    for (qsizetype index = 0; index < coreConnections.size(); ++index) {
        const QString suffix = index + 1 == coreConnections.size() ? QString() : QString(",");
        lines.append(coreConnections.at(index) + suffix);
    }
    lines.append(");");
    lines.append(QString());

    lines.append("always_comb begin");
    for (quint32 pin = 0; pin < plan.pinCount; ++pin) {
        for (quint32 slot = 0; slot < plan.hsSlots; ++slot) {
            lines.append(
                QString("    if (pin_%1_select_i == %2'd%3) begin").arg(pin).arg(width).arg(slot));
            lines.append(
                QString("        assert (pad_input_enable_w[%1] == (%2));")
                    .arg(pin)
                    .arg(expectedRoleExpression(plan, pin, slot, QSocIomuxRole::InputEnable)));
            lines.append(
                QString("        assert (pad_output_value_w[%1] == (%2));")
                    .arg(pin)
                    .arg(expectedRoleExpression(plan, pin, slot, QSocIomuxRole::OutputValue)));
            lines.append(
                QString("        assert (pad_output_enable_w[%1] == (%2));")
                    .arg(pin)
                    .arg(expectedRoleExpression(plan, pin, slot, QSocIomuxRole::OutputEnable)));
            lines.append("    end");
        }
        if (plan.hsSlots < (quint32(1) << width)) {
            lines.append(QString("    if (pin_%1_select_i >= %2'd%3) begin")
                             .arg(pin)
                             .arg(width)
                             .arg(plan.hsSlots));
            lines.append(QString("        assert (pad_input_enable_w[%1] == 1'b0);").arg(pin));
            lines.append(QString("        assert (pad_output_value_w[%1] == 1'b0);").arg(pin));
            lines.append(QString("        assert (pad_output_enable_w[%1] == 1'b0);").arg(pin));
            lines.append("    end");
        }
    }
    for (const QSocIomuxRoutePlan &route : plan.routes) {
        const QSocIomuxEndpointPlan &endpoint = route.inputValue;
        if (endpoint.link.isEmpty()) {
            continue;
        }
        const QString name = endpointPortName(route.pin, route.slot, QSocIomuxRole::InputValue);
        const QString expression = endpoint.invert
                                       ? QString("pad_input_value_i[%1] ^ 1'b1").arg(route.pin)
                                       : QString("pad_input_value_i[%1]").arg(route.pin);
        lines.append(QString("    assert (%1 == (%2));").arg(name, expression));
    }
    for (quint32 slot = 0; slot < plan.hsSlots; ++slot) {
        lines.append(QString("    cover (pin_0_select_i == %1'd%2);").arg(width).arg(slot));
        lines.append(QString("    cover (pin_%1_select_i == %2'd%3);")
                         .arg(plan.pinCount - 1)
                         .arg(width)
                         .arg(slot));
    }
    lines.append("end");
    lines.append(QString());
    lines.append("endmodule");
    lines.append(QString());
    return lines.join('\n');
}

QString buildSby(const QSocIomuxPlan &plan)
{
    return QStringLiteral(
               "[tasks]\n"
               "prove\n"
               "bmc\n"
               "cover\n"
               "\n"
               "[options]\n"
               "prove: mode prove\n"
               "prove: depth 4\n"
               "prove: aigsmt none\n"
               "bmc: mode bmc\n"
               "bmc: depth 4\n"
               "cover: mode cover\n"
               "cover: depth 4\n"
               "\n"
               "[engines]\n"
               "prove: abc pdr\n"
               "bmc: smtbmc z3\n"
               "cover: smtbmc z3\n"
               "\n"
               "[script]\n"
               "read -formal -sv %1.v %1_conn.v %1_hs_formal.sv\n"
               "prep -top %1_hs_formal\n"
               "\n"
               "[files]\n"
               "%1.v\n"
               "%1_conn.v\n"
               "%1_hs_formal.sv\n")
        .arg(plan.moduleName);
}

} // namespace

QSocIomuxFormalCollateral QSocIomuxFormal::generate(const QSocIomuxPlan &plan)
{
    QSocIomuxFormalCollateral collateral;
    if (plan.pinCount == 0 || plan.hsSlots == 0) {
        return collateral;
    }
    collateral.systemVerilog = buildSystemVerilog(plan);
    collateral.sby           = buildSby(plan);
    return collateral;
}
