// SPDX-License-Identifier: Apache-2.0
// SPDX-FileCopyrightText: 2026 Huang Rui <vowstar@gmail.com>

#include "common/qsociomuxformal.h"

#include <QRegularExpression>

#include "common/qsociomuxgenerator.h"

#include <QStringList>

namespace {

quint32 selectorWidth(quint32 hsSlots)
{
    if (hsSlots <= 2) {
        return 1;
    }
    if (hsSlots <= 4) {
        return 2;
    }
    return 3;
}

const QSocIomuxEndpointPlan &routeRole(const QSocIomuxRoutePlan &route, QSocIomuxRole role)
{
    switch (role) {
    case QSocIomuxRole::InputValue:
        return route.inputValue;
    case QSocIomuxRole::InputEnable:
        return route.inputEnable;
    case QSocIomuxRole::OutputValue:
        return route.outputValue;
    case QSocIomuxRole::OutputEnable:
        break;
    }
    return route.outputEnable;
}

const QSocIomuxRoutePlan *findRoute(const QSocIomuxPlan &plan, quint32 pin, quint32 slot)
{
    for (const QSocIomuxRoutePlan &route : plan.routes) {
        if (route.pin == pin && route.slot == slot) {
            return &route;
        }
    }
    return nullptr;
}

QString expectedRoleExpression(
    const QSocIomuxPlan &plan, quint32 pin, quint32 slot, QSocIomuxRole role)
{
    const QSocIomuxRoutePlan *route = findRoute(plan, pin, slot);
    if (route == nullptr) {
        return QStringLiteral("1'b0");
    }
    const QSocIomuxEndpointPlan &endpoint = routeRole(*route, role);
    if (!endpoint.link.isEmpty()) {
        const QString name = QSocIomuxGenerator::endpointPortName(pin, slot, role);
        return endpoint.invert ? name + " ^ 1'b1" : name;
    }
    if (endpoint.constant.has_value() && *endpoint.constant == 1) {
        return QStringLiteral("1'b1");
    }
    return QStringLiteral("1'b0");
}

QString buildSystemVerilog(const QSocIomuxPlan &plan)
{
    const quint32 width = selectorWidth(plan.hsSlots);
    const quint64 dense = quint64(plan.hsSlots) * plan.pinCount;

    QStringList txPorts;
    QStringList rxPorts;
    for (const QSocIomuxRoutePlan &route : plan.routes) {
        for (const QSocIomuxRole role :
             {QSocIomuxRole::InputValue,
              QSocIomuxRole::InputEnable,
              QSocIomuxRole::OutputValue,
              QSocIomuxRole::OutputEnable}) {
            const QSocIomuxEndpointPlan &endpoint = routeRole(route, role);
            if (endpoint.link.isEmpty()) {
                continue;
            }
            const QString name = QSocIomuxGenerator::endpointPortName(route.pin, route.slot, role);
            if (role == QSocIomuxRole::InputValue) {
                rxPorts.append(name);
            } else {
                txPorts.append(name);
            }
        }
    }

    QStringList lines;
    lines.append("// Generated by QSoC. Do not edit.");
    lines.append(QString("module %1_hs_formal (").arg(plan.moduleName));
    QStringList declarations;
    declarations.append(QString("    input logic [%1:0] pad_input_value_i").arg(plan.pinCount - 1));
    for (quint32 pin = 0; pin < plan.pinCount; ++pin) {
        declarations.append(
            QString("    input logic [%1:0] pin_%2_select_i").arg(width - 1).arg(pin));
    }
    for (const QString &name : txPorts) {
        declarations.append(QString("    input logic %1").arg(name));
    }
    for (qsizetype index = 0; index < declarations.size(); ++index) {
        const QString suffix = index + 1 == declarations.size() ? QString() : QString(",");
        lines.append(declarations.at(index) + suffix);
    }
    lines.append(");");
    lines.append(QString());
    lines.append(QString("logic [%1:0] tx_input_enable_w;").arg(dense - 1));
    lines.append(QString("logic [%1:0] tx_output_value_w;").arg(dense - 1));
    lines.append(QString("logic [%1:0] tx_output_enable_w;").arg(dense - 1));
    lines.append(QString("logic [%1:0] rx_input_value_w;").arg(dense - 1));
    lines.append(QString("logic [%1:0] pad_input_enable_w;").arg(plan.pinCount - 1));
    lines.append(QString("logic [%1:0] pad_output_value_w;").arg(plan.pinCount - 1));
    lines.append(QString("logic [%1:0] pad_output_enable_w;").arg(plan.pinCount - 1));
    for (const QString &name : rxPorts) {
        lines.append(QString("logic %1;").arg(name));
    }
    lines.append(QString());

    QStringList connConnections
        = {"    .tx_input_enable_o(tx_input_enable_w)",
           "    .tx_output_value_o(tx_output_value_w)",
           "    .tx_output_enable_o(tx_output_enable_w)",
           "    .rx_input_value_i(rx_input_value_w)"};
    for (const QSocIomuxRoutePlan &route : plan.routes) {
        for (const QSocIomuxRole role :
             {QSocIomuxRole::InputValue,
              QSocIomuxRole::InputEnable,
              QSocIomuxRole::OutputValue,
              QSocIomuxRole::OutputEnable}) {
            if (routeRole(route, role).link.isEmpty()) {
                continue;
            }
            const QString name = QSocIomuxGenerator::endpointPortName(route.pin, route.slot, role);
            connConnections.append(QString("    .%1(%1)").arg(name));
        }
    }
    lines.append(QString("%1_conn u_conn (").arg(plan.moduleName));
    for (qsizetype index = 0; index < connConnections.size(); ++index) {
        const QString suffix = index + 1 == connConnections.size() ? QString() : QString(",");
        lines.append(connConnections.at(index) + suffix);
    }
    lines.append(");");
    lines.append(QString());

    QStringList coreConnections
        = {"    .pad_input_value_i(pad_input_value_i)",
           "    .pad_input_enable_o(pad_input_enable_w)",
           "    .pad_output_value_o(pad_output_value_w)",
           "    .pad_output_enable_o(pad_output_enable_w)",
           "    .tx_input_enable_i(tx_input_enable_w)",
           "    .tx_output_value_i(tx_output_value_w)",
           "    .tx_output_enable_i(tx_output_enable_w)",
           "    .rx_input_value_o(rx_input_value_w)"};
    for (quint32 pin = 0; pin < plan.pinCount; ++pin) {
        coreConnections.append(QString("    .pin_%1_select_i(pin_%1_select_i)").arg(pin));
    }
    lines.append(QString("%1_core u_core (").arg(plan.moduleName));
    for (qsizetype index = 0; index < coreConnections.size(); ++index) {
        const QString suffix = index + 1 == coreConnections.size() ? QString() : QString(",");
        lines.append(coreConnections.at(index) + suffix);
    }
    lines.append(");");
    lines.append(QString());

    lines.append("always_comb begin");
    for (quint32 pin = 0; pin < plan.pinCount; ++pin) {
        for (quint32 slot = 0; slot < plan.hsSlots; ++slot) {
            lines.append(
                QString("    if (pin_%1_select_i == %2'd%3) begin").arg(pin).arg(width).arg(slot));
            lines.append(
                QString("        assert (pad_input_enable_w[%1] == (%2));")
                    .arg(pin)
                    .arg(expectedRoleExpression(plan, pin, slot, QSocIomuxRole::InputEnable)));
            lines.append(
                QString("        assert (pad_output_value_w[%1] == (%2));")
                    .arg(pin)
                    .arg(expectedRoleExpression(plan, pin, slot, QSocIomuxRole::OutputValue)));
            lines.append(
                QString("        assert (pad_output_enable_w[%1] == (%2));")
                    .arg(pin)
                    .arg(expectedRoleExpression(plan, pin, slot, QSocIomuxRole::OutputEnable)));
            lines.append("    end");
        }
        if (plan.hsSlots < (quint32(1) << width)) {
            lines.append(QString("    if (pin_%1_select_i >= %2'd%3) begin")
                             .arg(pin)
                             .arg(width)
                             .arg(plan.hsSlots));
            lines.append(QString("        assert (pad_input_enable_w[%1] == 1'b0);").arg(pin));
            lines.append(QString("        assert (pad_output_value_w[%1] == 1'b0);").arg(pin));
            lines.append(QString("        assert (pad_output_enable_w[%1] == 1'b0);").arg(pin));
            lines.append("    end");
        }
    }
    for (const QSocIomuxRoutePlan &route : plan.routes) {
        const QSocIomuxEndpointPlan &endpoint = route.inputValue;
        if (endpoint.link.isEmpty()) {
            continue;
        }
        const QString name
            = QSocIomuxGenerator::endpointPortName(route.pin, route.slot, QSocIomuxRole::InputValue);
        const QString expression = endpoint.invert
                                       ? QString("pad_input_value_i[%1] ^ 1'b1").arg(route.pin)
                                       : QString("pad_input_value_i[%1]").arg(route.pin);
        lines.append(QString("    assert (%1 == (%2));").arg(name, expression));
    }
    for (quint32 slot = 0; slot < plan.hsSlots; ++slot) {
        lines.append(QString("    cover (pin_0_select_i == %1'd%2);").arg(width).arg(slot));
        lines.append(QString("    cover (pin_%1_select_i == %2'd%3);")
                         .arg(plan.pinCount - 1)
                         .arg(width)
                         .arg(slot));
    }
    lines.append("end");
    lines.append(QString());
    lines.append("endmodule");
    lines.append(QString());
    return lines.join('\n');
}

QString buildSby(const QSocIomuxPlan &plan)
{
    return QStringLiteral(
               "[tasks]\n"
               "prove\n"
               "bmc\n"
               "cover\n"
               "\n"
               "[options]\n"
               "prove: mode prove\n"
               "prove: depth 4\n"
               "prove: aigsmt none\n"
               "bmc: mode bmc\n"
               "bmc: depth 4\n"
               "cover: mode cover\n"
               "cover: depth 4\n"
               "\n"
               "[engines]\n"
               "prove: abc pdr\n"
               "bmc: smtbmc z3\n"
               "cover: smtbmc z3\n"
               "\n"
               "[script]\n"
               "read -formal -sv %1.v %1_conn.v %1_hs_formal.sv\n"
               "prep -top %1_hs_formal\n"
               "\n"
               "[files]\n"
               "%1.v\n"
               "%1_conn.v\n"
               "%1_hs_formal.sv\n")
        .arg(plan.moduleName);
}

} // namespace

QSocIomuxFormalCollateral QSocIomuxFormal::generate(const QSocIomuxPlan &plan)
{
    QSocIomuxFormalCollateral collateral;
    if (plan.pinCount == 0 || plan.hsSlots == 0) {
        return collateral;
    }
    collateral.systemVerilog = buildSystemVerilog(plan);
    collateral.sby           = buildSby(plan);
    return collateral;
}

QSocIomuxFormalCollateral QSocIomuxFormal::generatePad(const QSocIomuxPlan &plan)
{
    const QSocPadCellPlan &cell = plan.integration.padCell;
    if (plan.pinCount == 0 || !cell.declared() || cell.constraint.isEmpty()) {
        return {};
    }
    const QString name = plan.moduleName;
    QStringList   sv;
    sv.append("// Generated by QSoC. Do not edit.");
    sv.append("`default_nettype none");
    sv.append(QString());

    /* A stub of the cell. Directions come from the module library, so a harness
     * that elaborates is one more check that the declaration named real ports. */
    QStringList stubPorts;
    for (auto it = cell.cellPorts.cbegin(); it != cell.cellPorts.cend(); ++it) {
        const QString dir = it.value() == "out"     ? QStringLiteral("output")
                            : it.value() == "inout" ? QStringLiteral("inout")
                                                    : QStringLiteral("input");
        stubPorts.append(QString("    %1 wire %2").arg(dir, it.key()));
    }
    sv.append(QString("module %1 (").arg(cell.cell));
    sv.append(stubPorts.join(",\n"));
    sv.append(");");
    /* An empty body reads as a blackbox and the flow refuses it. Every output
     * takes a free value instead, which is the honest model of a receiver the
     * proof knows nothing about. */
    for (auto it = cell.cellPorts.cbegin(); it != cell.cellPorts.cend(); ++it) {
        if (it.value() == "out") {
            sv.append(QString("(* anyseq *) reg %1_any;").arg(it.key()));
            sv.append(QString("assign %1 = %1_any;").arg(it.key()));
        }
    }
    sv.append("endmodule");
    sv.append(QString());

    /* Free inputs of the pad module become free inputs of the harness. */
    const QString range = QString("[%1:0]").arg(plan.pinCount - 1);
    QStringList   harnessPorts;
    QStringList   padConnections = {"    .pad_io(pad_io)"};
    sv.append(QString("module %1_pad_formal (").arg(name));
    if (!cell.portInputEnable.isEmpty()) {
        harnessPorts.append(QString("    input wire %1 pad_input_enable_i").arg(range));
        padConnections.append("    .pad_input_enable_i(pad_input_enable_i)");
    }
    if (!cell.portOutputValue.isEmpty()) {
        harnessPorts.append(QString("    input wire %1 pad_output_value_i").arg(range));
        padConnections.append("    .pad_output_value_i(pad_output_value_i)");
    }
    if (!cell.portOutputEnable.isEmpty()) {
        harnessPorts.append(QString("    input wire %1 pad_output_enable_i").arg(range));
        padConnections.append("    .pad_output_enable_i(pad_output_enable_i)");
    }
    quint32   pullWidth = 0;
    qsizetype pullRows  = 0;
    for (auto it = cell.pull.mode.cbegin(); it != cell.pull.mode.cend(); ++it) {
        pullRows += it.value().size();
    }
    if (pullRows > 0) {
        pullWidth = 1;
        while ((qsizetype(1) << pullWidth) < pullRows) {
            ++pullWidth;
        }
        harnessPorts.append(QString("    input wire [%1:0] pad_pull_select_i")
                                .arg(quint64(pullWidth) * plan.pinCount - 1));
        padConnections.append("    .pad_pull_select_i(pad_pull_select_i)");
        if (cell.canKeep() && !cell.keeperIsNative()) {
            harnessPorts.append(QString("    input wire %1 pad_keep_i").arg(range));
            harnessPorts.append(QString("    input wire %1 pad_osc_i").arg(range));
            padConnections.append("    .pad_keep_i(pad_keep_i)");
            padConnections.append("    .pad_osc_i(pad_osc_i)");
        }
    }
    if (!cell.drive.level.isEmpty()) {
        quint32 driveWidth = 1;
        while ((qsizetype(1) << driveWidth) < cell.drive.level.size()) {
            ++driveWidth;
        }
        harnessPorts.append(QString("    input wire [%1:0] pad_drive_select_i")
                                .arg(quint64(driveWidth) * plan.pinCount - 1));
        padConnections.append("    .pad_drive_select_i(pad_drive_select_i)");
    }
    sv.append(harnessPorts.join(",\n"));
    sv.append(");");
    sv.append(QString("wire %1 pad_io;").arg(range));
    if (!cell.portInputValue.isEmpty()) {
        sv.append(QString("wire %1 pad_input_value_o;").arg(range));
        padConnections.append("    .pad_input_value_o(pad_input_value_o)");
    }
    sv.append(QString("%1_pad u_pad (").arg(name));
    sv.append(padConnections.join(",\n"));
    sv.append(");");
    sv.append(QString());

    sv.append(QString());
    sv.append("endmodule");
    sv.append("`default_nettype wire");
    sv.append(QString());

    const QString sby = QStringLiteral(
                            "[tasks]\n"
                            "prove\n"
                            "bmc\n"
                            "\n"
                            "[options]\n"
                            "multiclock on\n"
                            "prove: mode prove\n"
                            "prove: depth 4\n"
                            "bmc: mode bmc\n"
                            "bmc: depth 4\n"
                            "\n"
                            "[engines]\n"
                            "prove: smtbmc z3\n"
                            "bmc: smtbmc z3\n"
                            "\n"
                            "[script]\n"
                            "read -formal -sv %1_pad.v %1_pad_formal.sv\n"
                            "prep -top %1_pad_formal -flatten\n"
                            "\n"
                            "[files]\n"
                            "%1_pad.v\n"
                            "%1_pad_formal.sv\n")
                            .arg(name);
    return {sv.join('\n'), sby};
}
