// SPDX-License-Identifier: Apache-2.0
// SPDX-FileCopyrightText: 2026 Huang Rui <vowstar@gmail.com>

#include "common/qsocmmiouvm.h"

#include "common/qsocmmiogenerator.h"

#include <limits>
#include <optional>
#include <QSet>
#include <QStringList>

namespace {

QString packedRange(quint32 width)
{
    return width == 1 ? QString() : QString(" [%1:0]").arg(width - 1);
}

QString bitRange(const QSocMmioFieldPlan &field)
{
    return field.width == 1 ? QString("[%1]").arg(field.lsb)
                            : QString("[%1:%2]").arg(field.lsb + field.width - 1).arg(field.lsb);
}

quint64 widthMask(quint32 width)
{
    return width == 64 ? std::numeric_limits<quint64>::max() : (quint64(1) << width) - 1;
}

quint64 fieldMask(const QSocMmioFieldPlan &field)
{
    return widthMask(field.width) << field.lsb;
}

QString literal(quint32 width, quint64 value)
{
    const int digits = static_cast<int>((width + 3) / 4);
    return QString("%1'h%2").arg(width).arg(value & widthMask(width), digits, 16, QLatin1Char('0'));
}

QString addressLiteral(const QSocMmioPlan &plan, quint64 value)
{
    return literal(plan.addressWidth, value);
}

QString dataLiteral(const QSocMmioPlan &plan, quint64 value)
{
    return literal(plan.dataWidth, value);
}

QString strobeLiteral(const QSocMmioPlan &plan, quint64 value)
{
    return literal(plan.dataWidth / 8, value);
}

quint64 writableMask(const QSocMmioRegisterPlan &reg)
{
    quint64 mask = 0;
    for (const QSocMmioFieldPlan &field : reg.fields) {
        if (field.access == QSocMmioAccess::ReadWrite) {
            mask |= fieldMask(field);
        }
    }
    return mask;
}

/**
 * @brief Bits a write of one clears, the union of the write-one-clear fields.
 */
quint64 clearMask(const QSocMmioRegisterPlan &reg)
{
    quint64 mask = 0;
    for (const QSocMmioFieldPlan &field : reg.fields) {
        if (field.access == QSocMmioAccess::WriteOneClear) {
            mask |= fieldMask(field);
        }
    }
    return mask;
}

bool hasClearFields(const QSocMmioPlan &plan)
{
    for (const QSocMmioRegisterPlan &reg : plan.registers) {
        if (clearMask(reg) != 0) {
            return true;
        }
    }
    return false;
}

quint64 resetValue(const QSocMmioRegisterPlan &reg)
{
    quint64 value = 0;
    for (const QSocMmioFieldPlan &field : reg.fields) {
        if (qsocMmioHasStorage(field.access) && field.resetValue) {
            value |= (*field.resetValue & widthMask(field.width)) << field.lsb;
        }
    }
    return value;
}

quint64 writePattern(const QSocMmioPlan &plan, qsizetype registerIndex, quint32 lane)
{
    quint64 value = 0;
    for (quint32 byte = 0; byte < plan.dataWidth / 8; ++byte) {
        const quint64 pattern = (quint64(0x31) + quint64(registerIndex) * 0x17
                                 + quint64(lane) * 0x29 + quint64(byte) * 0x13)
                                & 0xff;
        value |= pattern << (byte * 8);
    }
    return value;
}

bool addressFits(const QSocMmioPlan &plan, quint64 address)
{
    return plan.addressWidth == 64 || address < (quint64(1) << plan.addressWidth);
}

std::optional<quint64> unmappedAddress(const QSocMmioPlan &plan)
{
    QSet<quint64> mapped;
    for (const QSocMmioRegisterPlan &reg : plan.registers) {
        mapped.insert(reg.byteOffset);
    }

    const quint64 bytes = plan.dataWidth / 8;
    for (qsizetype index = 0; index <= plan.registers.size(); ++index) {
        const quint64 candidate = quint64(index) * bytes;
        if (addressFits(plan, candidate) && !mapped.contains(candidate)) {
            return candidate;
        }
    }
    return std::nullopt;
}

QString buildInterface(const QSocMmioPlan &plan)
{
    QStringList lines = {
        "// Generated by QSoC. Do not edit.",
        QString("interface %1_uvm_if;").arg(plan.moduleName),
        "    logic clk_i;",
        "    logic rst_ni;",
        QString("    logic [%1:0] s_axi_awaddr;").arg(plan.addressWidth - 1),
        "    logic [2:0] s_axi_awprot;",
        "    logic s_axi_awvalid;",
        "    logic s_axi_awready;",
        QString("    logic [%1:0] s_axi_wdata;").arg(plan.dataWidth - 1),
        QString("    logic [%1:0] s_axi_wstrb;").arg(plan.dataWidth / 8 - 1),
        "    logic s_axi_wvalid;",
        "    logic s_axi_wready;",
        "    logic [1:0] s_axi_bresp;",
        "    logic s_axi_bvalid;",
        "    logic s_axi_bready;",
        QString("    logic [%1:0] s_axi_araddr;").arg(plan.addressWidth - 1),
        "    logic [2:0] s_axi_arprot;",
        "    logic s_axi_arvalid;",
        "    logic s_axi_arready;",
        QString("    logic [%1:0] s_axi_rdata;").arg(plan.dataWidth - 1),
        "    logic [1:0] s_axi_rresp;",
        "    logic s_axi_rvalid;",
        "    logic s_axi_rready;",
    };
    for (const QSocMmioRegisterPlan &reg : plan.registers) {
        for (const QSocMmioFieldPlan &field : reg.fields) {
            if (!field.inputPort.isEmpty()) {
                lines.append(
                    QString("    logic%1 %2;").arg(packedRange(field.width), field.inputPort));
            }
            if (!field.outputPort.isEmpty()) {
                lines.append(
                    QString("    logic%1 %2;").arg(packedRange(field.width), field.outputPort));
            }
        }
    }
    lines.append("endinterface");
    return lines.join('\n') + '\n';
}

void appendItem(QStringList *lines, const QSocMmioPlan &plan)
{
    const QString prefix = plan.moduleName + QStringLiteral("_uvm");
    lines->append(QString("    class %1_item extends uvm_sequence_item;").arg(prefix));
    lines->append("        bit write;");
    lines->append("        addr_t address;");
    lines->append("        data_t data;");
    lines->append("        strb_t strobe;");
    lines->append("        int unsigned write_order;");
    lines->append("        bit hold_response;");
    lines->append("        bit [1:0] response;");
    lines->append(QString("        `uvm_object_utils(%1_item)").arg(prefix));
    lines->append(QString());
    lines->append(QString("        function new(string name = \"%1_item\");").arg(prefix));
    lines->append("            super.new(name);");
    lines->append("        endfunction");
    lines->append("    endclass");
    lines->append(QString());
}

void appendDriver(QStringList *lines, const QSocMmioPlan &plan)
{
    const QString prefix        = plan.moduleName + QStringLiteral("_uvm");
    const QString interfaceName = prefix + QStringLiteral("_if");
    lines->append(QString("    class %1_driver extends uvm_driver #(%1_item);").arg(prefix));
    lines->append(QString("        `uvm_component_utils(%1_driver)").arg(prefix));
    lines->append(QString("        virtual %1 vif;").arg(interfaceName));
    lines->append(QString());
    lines->append(
        QString("        function new(string name = \"%1_driver\", uvm_component parent = null);")
            .arg(prefix));
    lines->append("            super.new(name, parent);");
    lines->append("        endfunction");
    lines->append(QString());
    lines->append("        function void build_phase(uvm_phase phase);");
    lines->append("            super.build_phase(phase);");
    lines->append(
        QString("            if (!uvm_config_db #(virtual %1)::get(this, \"\", \"vif\", vif))")
            .arg(interfaceName));
    lines->append(
        "                `uvm_fatal(\"NO_VIF\", \"MMIO virtual interface was not configured\")");
    lines->append("        endfunction");
    lines->append(QString());
    lines->append(QString("        task send_aw(%1_item item);").arg(prefix));
    lines->append("            int unsigned wait_cycles;");
    lines->append("            @(negedge vif.clk_i);");
    lines->append("            vif.s_axi_awaddr = item.address;");
    lines->append("            vif.s_axi_awvalid = 1'b1;");
    lines->append("            wait_cycles = 0;");
    lines->append("            do begin");
    lines->append("                @(posedge vif.clk_i);");
    lines->append("                if (++wait_cycles > CHANNEL_TIMEOUT_CYCLES)");
    lines->append(
        "                    `uvm_fatal(\"AW_TIMEOUT\", \"write address was not accepted\")");
    lines->append("            end while (vif.s_axi_awready !== 1'b1);");
    lines->append("            @(negedge vif.clk_i);");
    lines->append("            vif.s_axi_awvalid = 1'b0;");
    lines->append("        endtask");
    lines->append(QString());
    lines->append(QString("        task send_w(%1_item item);").arg(prefix));
    lines->append("            int unsigned wait_cycles;");
    lines->append("            @(negedge vif.clk_i);");
    lines->append("            vif.s_axi_wdata = item.data;");
    lines->append("            vif.s_axi_wstrb = item.strobe;");
    lines->append("            vif.s_axi_wvalid = 1'b1;");
    lines->append("            wait_cycles = 0;");
    lines->append("            do begin");
    lines->append("                @(posedge vif.clk_i);");
    lines->append("                if (++wait_cycles > CHANNEL_TIMEOUT_CYCLES)");
    lines->append("                    `uvm_fatal(\"W_TIMEOUT\", \"write data was not accepted\")");
    lines->append("            end while (vif.s_axi_wready !== 1'b1);");
    lines->append("            @(negedge vif.clk_i);");
    lines->append("            vif.s_axi_wvalid = 1'b0;");
    lines->append("        endtask");
    lines->append(QString());
    lines->append(QString("        task drive_write(%1_item item);").arg(prefix));
    lines->append("            bit [1:0] held_response;");
    lines->append("            int unsigned wait_cycles;");
    lines->append("            case (item.write_order)");
    lines->append("                WRITE_AW_FIRST: begin");
    lines->append("                    send_aw(item);");
    lines->append("                    send_w(item);");
    lines->append("                end");
    lines->append("                WRITE_W_FIRST: begin");
    lines->append("                    send_w(item);");
    lines->append("                    send_aw(item);");
    lines->append("                end");
    lines->append("                default: fork");
    lines->append("                    send_aw(item);");
    lines->append("                    send_w(item);");
    lines->append("                join");
    lines->append("            endcase");
    lines->append("            if (item.hold_response) begin");
    lines->append("                @(negedge vif.clk_i);");
    lines->append("                if (!vif.s_axi_bvalid)");
    lines->append(
        "                    `uvm_fatal(\"B_TIMEOUT\", \"write response was not produced\")");
    lines->append("                held_response = vif.s_axi_bresp;");
    lines->append("                @(negedge vif.clk_i);");
    lines->append("                if (!vif.s_axi_bvalid || vif.s_axi_bresp !== held_response)");
    lines->append(
        "                    `uvm_fatal(\"B_STABILITY\", \"write response changed while "
        "stalled\")");
    lines->append("            end");
    lines->append("            vif.s_axi_bready = 1'b1;");
    lines->append("            wait_cycles = 0;");
    lines->append("            do begin");
    lines->append("                @(posedge vif.clk_i);");
    lines->append("                if (++wait_cycles > CHANNEL_TIMEOUT_CYCLES)");
    lines->append(
        "                    `uvm_fatal(\"B_TIMEOUT\", \"write response was not produced\")");
    lines->append("            end while (vif.s_axi_bvalid !== 1'b1);");
    lines->append("            @(negedge vif.clk_i);");
    lines->append("            vif.s_axi_bready = 1'b0;");
    lines->append("        endtask");
    lines->append(QString());
    lines->append(QString("        task drive_read(%1_item item);").arg(prefix));
    lines->append("            bit [1:0] held_response;");
    lines->append("            data_t held_data;");
    lines->append("            int unsigned wait_cycles;");
    lines->append("            @(negedge vif.clk_i);");
    lines->append("            vif.s_axi_araddr = item.address;");
    lines->append("            vif.s_axi_arvalid = 1'b1;");
    lines->append("            wait_cycles = 0;");
    lines->append("            do begin");
    lines->append("                @(posedge vif.clk_i);");
    lines->append("                if (++wait_cycles > CHANNEL_TIMEOUT_CYCLES)");
    lines->append(
        "                    `uvm_fatal(\"AR_TIMEOUT\", \"read address was not accepted\")");
    lines->append("            end while (vif.s_axi_arready !== 1'b1);");
    lines->append("            @(negedge vif.clk_i);");
    lines->append("            vif.s_axi_arvalid = 1'b0;");
    lines->append("            if (item.hold_response) begin");
    lines->append("                @(negedge vif.clk_i);");
    lines->append("                if (!vif.s_axi_rvalid)");
    lines->append(
        "                    `uvm_fatal(\"R_TIMEOUT\", \"read response was not produced\")");
    lines->append("                held_response = vif.s_axi_rresp;");
    lines->append("                held_data = vif.s_axi_rdata;");
    lines->append("                @(negedge vif.clk_i);");
    lines->append("                if (!vif.s_axi_rvalid || vif.s_axi_rresp !== held_response");
    lines->append("                    || vif.s_axi_rdata !== held_data)");
    lines->append(
        "                    `uvm_fatal(\"R_STABILITY\", \"read response changed while stalled\")");
    lines->append("            end");
    lines->append("            vif.s_axi_rready = 1'b1;");
    lines->append("            wait_cycles = 0;");
    lines->append("            do begin");
    lines->append("                @(posedge vif.clk_i);");
    lines->append("                if (++wait_cycles > CHANNEL_TIMEOUT_CYCLES)");
    lines->append(
        "                    `uvm_fatal(\"R_TIMEOUT\", \"read response was not produced\")");
    lines->append("            end while (vif.s_axi_rvalid !== 1'b1);");
    lines->append("            @(negedge vif.clk_i);");
    lines->append("            vif.s_axi_rready = 1'b0;");
    lines->append("        endtask");
    lines->append(QString());
    lines->append("        task run_phase(uvm_phase phase);");
    lines->append(QString("            %1_item item;").arg(prefix));
    lines->append("            vif.s_axi_awaddr = '0;");
    lines->append("            vif.s_axi_awprot = '0;");
    lines->append("            vif.s_axi_awvalid = 1'b0;");
    lines->append("            vif.s_axi_wdata = '0;");
    lines->append("            vif.s_axi_wstrb = '0;");
    lines->append("            vif.s_axi_wvalid = 1'b0;");
    lines->append("            vif.s_axi_bready = 1'b0;");
    lines->append("            vif.s_axi_araddr = '0;");
    lines->append("            vif.s_axi_arprot = '0;");
    lines->append("            vif.s_axi_arvalid = 1'b0;");
    lines->append("            vif.s_axi_rready = 1'b0;");
    lines->append("            wait (vif.rst_ni === 1'b1);");
    lines->append("            forever begin");
    lines->append("                seq_item_port.get_next_item(item);");
    lines->append("                if (item.write)");
    lines->append("                    drive_write(item);");
    lines->append("                else");
    lines->append("                    drive_read(item);");
    lines->append("                seq_item_port.item_done();");
    lines->append("            end");
    lines->append("        endtask");
    lines->append("    endclass");
    lines->append(QString());
}

void appendMonitor(QStringList *lines, const QSocMmioPlan &plan)
{
    const QString prefix        = plan.moduleName + QStringLiteral("_uvm");
    const QString interfaceName = prefix + QStringLiteral("_if");
    lines->append(QString("    class %1_monitor extends uvm_monitor;").arg(prefix));
    lines->append(QString("        `uvm_component_utils(%1_monitor)").arg(prefix));
    lines->append(QString("        virtual %1 vif;").arg(interfaceName));
    lines->append(QString("        uvm_analysis_port #(%1_item) observed;").arg(prefix));
    lines->append("        bit aw_pending;");
    lines->append("        bit w_pending;");
    lines->append("        bit ar_pending;");
    lines->append(QString());
    lines->append(
        QString("        function new(string name = \"%1_monitor\", uvm_component parent = null);")
            .arg(prefix));
    lines->append("            super.new(name, parent);");
    lines->append("            observed = new(\"observed\", this);");
    lines->append("        endfunction");
    lines->append(QString());
    lines->append("        function void build_phase(uvm_phase phase);");
    lines->append("            super.build_phase(phase);");
    lines->append(
        QString("            if (!uvm_config_db #(virtual %1)::get(this, \"\", \"vif\", vif))")
            .arg(interfaceName));
    lines->append(
        "                `uvm_fatal(\"NO_VIF\", \"MMIO virtual interface was not configured\")");
    lines->append("        endfunction");
    lines->append(QString());
    lines->append("        function bit is_idle();");
    lines->append("            return !aw_pending && !w_pending && !ar_pending");
    lines->append("                && vif.s_axi_awvalid === 1'b0");
    lines->append("                && vif.s_axi_wvalid === 1'b0");
    lines->append("                && vif.s_axi_arvalid === 1'b0");
    lines->append("                && vif.s_axi_bvalid === 1'b0");
    lines->append("                && vif.s_axi_rvalid === 1'b0;");
    lines->append("        endfunction");
    lines->append(QString());
    lines->append("        task run_phase(uvm_phase phase);");
    lines->append("            bit b_held;");
    lines->append("            bit r_held;");
    lines->append("            addr_t aw_address;");
    lines->append("            addr_t ar_address;");
    lines->append("            data_t write_data;");
    lines->append("            strb_t write_strobe;");
    lines->append("            bit [1:0] held_bresp;");
    lines->append("            bit [1:0] held_rresp;");
    lines->append("            data_t held_rdata;");
    lines->append(QString("            %1_item item;").arg(prefix));
    lines->append("            aw_pending = 1'b0;");
    lines->append("            w_pending = 1'b0;");
    lines->append("            ar_pending = 1'b0;");
    lines->append("            b_held = 1'b0;");
    lines->append("            r_held = 1'b0;");
    lines->append("            forever begin");
    lines->append("                @(posedge vif.clk_i);");
    lines->append("                if (!vif.rst_ni) begin");
    lines->append("                    if (vif.s_axi_awready !== 1'b0");
    lines->append("                        || vif.s_axi_wready !== 1'b0");
    lines->append("                        || vif.s_axi_arready !== 1'b0");
    lines->append("                        || vif.s_axi_bvalid !== 1'b0");
    lines->append("                        || vif.s_axi_rvalid !== 1'b0)");
    lines->append(
        "                        `uvm_fatal(\"RESET\", \"MMIO bus was not idle during reset\")");
    lines->append("                    aw_pending = 1'b0;");
    lines->append("                    w_pending = 1'b0;");
    lines->append("                    ar_pending = 1'b0;");
    lines->append("                    b_held = 1'b0;");
    lines->append("                    r_held = 1'b0;");
    lines->append("                end else begin");
    lines->append("                    if (b_held");
    lines->append(
        "                        && (!vif.s_axi_bvalid || vif.s_axi_bresp !== held_bresp))");
    lines->append(
        "                        `uvm_fatal(\"B_STABILITY\", \"write response changed while "
        "stalled\")");
    lines->append("                    if (r_held && (!vif.s_axi_rvalid");
    lines->append("                        || vif.s_axi_rresp !== held_rresp");
    lines->append("                        || vif.s_axi_rdata !== held_rdata))");
    lines->append(
        "                        `uvm_fatal(\"R_STABILITY\", \"read response changed while "
        "stalled\")");
    lines->append("                    b_held = vif.s_axi_bvalid && !vif.s_axi_bready;");
    lines->append("                    r_held = vif.s_axi_rvalid && !vif.s_axi_rready;");
    lines->append("                    if (b_held)");
    lines->append("                        held_bresp = vif.s_axi_bresp;");
    lines->append("                    if (r_held) begin");
    lines->append("                        held_rresp = vif.s_axi_rresp;");
    lines->append("                        held_rdata = vif.s_axi_rdata;");
    lines->append("                    end");
    lines->append("                    if (vif.s_axi_bvalid === 1'b1");
    lines->append("                        && (!aw_pending || !w_pending))");
    lines->append(
        "                        `uvm_fatal(\"B_ORDER\", \"write response lacked a request\")");
    lines->append("                    if (vif.s_axi_bvalid === 1'b1");
    lines->append("                        && vif.s_axi_bresp !== RESP_OKAY");
    lines->append("                        && vif.s_axi_bresp !== RESP_SLVERR)");
    lines->append(
        "                        `uvm_fatal(\"B_RESPONSE\", \"write response was not supported\")");
    lines->append(
        "                    if (vif.s_axi_bvalid === 1'b1 && vif.s_axi_bready === 1'b1) begin");
    lines->append(
        QString("                        item = %1_item::type_id::create(\"observed_write\");")
            .arg(prefix));
    lines->append("                        item.write = 1'b1;");
    lines->append("                        item.address = aw_address;");
    lines->append("                        item.data = write_data;");
    lines->append("                        item.strobe = write_strobe;");
    lines->append("                        item.response = vif.s_axi_bresp;");
    lines->append("                        observed.write(item);");
    lines->append("                        aw_pending = 1'b0;");
    lines->append("                        w_pending = 1'b0;");
    lines->append("                    end");
    lines->append("                    if (vif.s_axi_awvalid && vif.s_axi_awready) begin");
    lines->append("                        if (aw_pending)");
    lines->append(
        "                            `uvm_fatal(\"AW_ORDER\", \"second write address was "
        "accepted\")");
    lines->append("                        aw_pending = 1'b1;");
    lines->append("                        aw_address = vif.s_axi_awaddr;");
    lines->append("                    end");
    lines->append("                    if (vif.s_axi_wvalid && vif.s_axi_wready) begin");
    lines->append("                        if (w_pending)");
    lines->append(
        "                            `uvm_fatal(\"W_ORDER\", \"second write data was accepted\")");
    lines->append("                        w_pending = 1'b1;");
    lines->append("                        write_data = vif.s_axi_wdata;");
    lines->append("                        write_strobe = vif.s_axi_wstrb;");
    lines->append("                    end");
    lines->append("                    if (vif.s_axi_rvalid === 1'b1 && !ar_pending)");
    lines->append(
        "                        `uvm_fatal(\"R_ORDER\", \"read response lacked a request\")");
    lines->append("                    if (vif.s_axi_rvalid === 1'b1");
    lines->append("                        && vif.s_axi_rresp !== RESP_OKAY");
    lines->append("                        && vif.s_axi_rresp !== RESP_SLVERR)");
    lines->append(
        "                        `uvm_fatal(\"R_RESPONSE\", \"read response was not supported\")");
    lines->append(
        "                    if (vif.s_axi_rvalid === 1'b1 && vif.s_axi_rready === 1'b1) begin");
    lines->append(
        QString("                        item = %1_item::type_id::create(\"observed_read\");")
            .arg(prefix));
    lines->append("                        item.write = 1'b0;");
    lines->append("                        item.address = ar_address;");
    lines->append("                        item.data = vif.s_axi_rdata;");
    lines->append("                        item.strobe = '0;");
    lines->append("                        item.response = vif.s_axi_rresp;");
    lines->append("                        observed.write(item);");
    lines->append("                        ar_pending = 1'b0;");
    lines->append("                    end");
    lines->append("                    if (vif.s_axi_arvalid && vif.s_axi_arready) begin");
    lines->append("                        if (ar_pending)");
    lines->append(
        "                            `uvm_fatal(\"AR_ORDER\", \"second read address was "
        "accepted\")");
    lines->append("                        ar_pending = 1'b1;");
    lines->append("                        ar_address = vif.s_axi_araddr;");
    lines->append("                    end");
    lines->append("                end");
    lines->append("            end");
    lines->append("        endtask");
    lines->append("    endclass");
    lines->append(QString());
}

void appendScoreboard(QStringList *lines, const QSocMmioPlan &plan)
{
    const QString prefix        = plan.moduleName + QStringLiteral("_uvm");
    const QString interfaceName = prefix + QStringLiteral("_if");
    lines->append(QString("    class %1_scoreboard extends uvm_subscriber #(%1_item);").arg(prefix));
    lines->append(QString("        `uvm_component_utils(%1_scoreboard)").arg(prefix));
    lines->append(QString("        virtual %1 vif;").arg(interfaceName));
    lines->append("        int unsigned observed_count;");
    for (qsizetype index = 0; index < plan.registers.size(); ++index) {
        lines->append(QString("        data_t reference_%1;").arg(index));
    }
    lines->append(QString());
    lines->append(
        QString(
            "        function new(string name = \"%1_scoreboard\", uvm_component parent = null);")
            .arg(prefix));
    lines->append("            super.new(name, parent);");
    lines->append("        endfunction");
    lines->append(QString());
    lines->append("        function void reset_model();");
    for (qsizetype index = 0; index < plan.registers.size(); ++index) {
        lines->append(QString("            reference_%1 = %2;")
                          .arg(index)
                          .arg(dataLiteral(plan, resetValue(plan.registers.at(index)))));
    }
    lines->append("        endfunction");
    lines->append(QString());
    lines->append("        function void build_phase(uvm_phase phase);");
    lines->append("            super.build_phase(phase);");
    lines->append(
        QString("            if (!uvm_config_db #(virtual %1)::get(this, \"\", \"vif\", vif))")
            .arg(interfaceName));
    lines->append(
        "                `uvm_fatal(\"NO_VIF\", \"MMIO virtual interface was not configured\")");
    lines->append("            observed_count = 0;");
    lines->append("            reset_model();");
    lines->append("        endfunction");
    lines->append(QString());
    lines->append("        function bit address_mapped(addr_t address);");
    lines->append("            case (address)");
    for (const QSocMmioRegisterPlan &reg : plan.registers) {
        lines->append(QString("                %1: address_mapped = 1'b1;")
                          .arg(addressLiteral(plan, reg.byteOffset)));
    }
    lines->append("                default: address_mapped = 1'b0;");
    lines->append("            endcase");
    lines->append("        endfunction");
    lines->append(QString());
    lines->append("        function data_t expected_read(addr_t address);");
    lines->append("            expected_read = '0;");
    lines->append("            case (address)");
    for (qsizetype registerIndex = 0; registerIndex < plan.registers.size(); ++registerIndex) {
        const QSocMmioRegisterPlan &reg = plan.registers.at(registerIndex);
        lines->append(
            QString("                %1: begin").arg(addressLiteral(plan, reg.byteOffset)));
        lines->append(
            QString("                    expected_read = reference_%1;").arg(registerIndex));
        for (const QSocMmioFieldPlan &field : reg.fields) {
            if (field.access == QSocMmioAccess::ReadOnly && field.constantValue) {
                lines->append(QString("                    expected_read%1 = %2;")
                                  .arg(bitRange(field), literal(field.width, *field.constantValue)));
            } else if (field.access == QSocMmioAccess::ReadOnly && !field.inputPort.isEmpty()) {
                lines->append(QString("                    expected_read%1 = vif.%2;")
                                  .arg(bitRange(field), field.inputPort));
            }
        }
        lines->append("                end");
    }
    lines->append("                default: expected_read = '0;");
    lines->append("            endcase");
    lines->append("        endfunction");
    lines->append(QString());
    lines->append("        function void apply_write(addr_t address, data_t data, strb_t strobe);");
    lines->append("            data_t byte_mask;");
    lines->append("            byte_mask = '0;");
    lines->append("            for (int unsigned lane = 0; lane < STRB_WIDTH; ++lane) begin");
    lines->append("                if (strobe[lane])");
    lines->append("                    byte_mask[lane * 8 +: 8] = '1;");
    lines->append("            end");
    lines->append("            case (address)");
    for (qsizetype registerIndex = 0; registerIndex < plan.registers.size(); ++registerIndex) {
        const QSocMmioRegisterPlan &reg   = plan.registers.at(registerIndex);
        const quint64               mask  = writableMask(reg);
        const quint64               clear = clearMask(reg);
        lines->append(
            QString("                %1: begin").arg(addressLiteral(plan, reg.byteOffset)));
        lines->append(
            QString("                    reference_%1 = (reference_%1 & ~(byte_mask & %2))")
                .arg(registerIndex)
                .arg(dataLiteral(plan, mask)));
        lines->append(QString("                        | (data & byte_mask & %1);")
                          .arg(dataLiteral(plan, mask)));
        if (clear != 0) {
            lines->append(
                QString(
                    "                    reference_%1 = reference_%1 & ~(data & byte_mask & %2);")
                    .arg(registerIndex)
                    .arg(dataLiteral(plan, clear)));
        }
        lines->append("                end");
    }
    lines->append("                default: begin end");
    lines->append("            endcase");
    lines->append("        endfunction");
    lines->append(QString());
    lines->append("        function void check_outputs(addr_t address);");
    lines->append("            case (address)");
    for (qsizetype registerIndex = 0; registerIndex < plan.registers.size(); ++registerIndex) {
        const QSocMmioRegisterPlan &reg       = plan.registers.at(registerIndex);
        bool                        hasOutput = false;
        for (const QSocMmioFieldPlan &field : reg.fields) {
            hasOutput = hasOutput || !field.outputPort.isEmpty();
        }
        if (!hasOutput) {
            continue;
        }
        lines->append(
            QString("                %1: begin").arg(addressLiteral(plan, reg.byteOffset)));
        for (const QSocMmioFieldPlan &field : reg.fields) {
            if (field.outputPort.isEmpty()) {
                continue;
            }
            lines->append(QString("                    if (vif.%1 !== reference_%2%3)")
                              .arg(field.outputPort)
                              .arg(registerIndex)
                              .arg(bitRange(field)));
            lines->append(QString(
                              "                        `uvm_fatal(\"OUTPUT\", \"%1 did not match "
                              "the register model\")")
                              .arg(field.outputPort));
        }
        lines->append("                end");
    }
    lines->append("                default: begin end");
    lines->append("            endcase");
    lines->append("        endfunction");
    lines->append(QString());
    if (hasClearFields(plan)) {
        /* The sequence pulses a set source only while the bus is idle, so this
         * sampler and apply_write never touch one reference on the same cycle. */
        lines->append("        task run_phase(uvm_phase phase);");
        lines->append("            forever begin");
        lines->append("                @(posedge vif.clk_i);");
        lines->append("                if (vif.rst_ni === 1'b1) begin");
        for (qsizetype registerIndex = 0; registerIndex < plan.registers.size(); ++registerIndex) {
            for (const QSocMmioFieldPlan &field : plan.registers.at(registerIndex).fields) {
                if (field.access != QSocMmioAccess::WriteOneClear) {
                    continue;
                }
                lines->append(
                    QString("                    if (vif.%1 === 1'b1)").arg(field.inputPort));
                lines->append(QString("                        reference_%1%2 = 1'b1;")
                                  .arg(registerIndex)
                                  .arg(bitRange(field)));
            }
        }
        lines->append("                end");
        lines->append("            end");
        lines->append("        endtask");
        lines->append(QString());
    }
    lines->append(QString("        function void write(%1_item item);").arg(prefix));
    lines->append("            bit [1:0] expected_response;");
    lines->append(
        "            expected_response = address_mapped(item.address) ? RESP_OKAY : RESP_SLVERR;");
    lines->append("            if (item.response !== expected_response)");
    lines->append(
        "                `uvm_fatal(\"RESPONSE\", $sformatf(\"address %0h response %0h expected "
        "%0h\",");
    lines->append("                    item.address, item.response, expected_response))");
    lines->append("            if (item.write) begin");
    lines->append("                if (address_mapped(item.address)) begin");
    lines->append("                    apply_write(item.address, item.data, item.strobe);");
    lines->append("                end");
    lines->append("            end else if (item.data !== expected_read(item.address)) begin");
    lines->append(
        "                `uvm_fatal(\"READ_DATA\", $sformatf(\"address %0h data %0h expected "
        "%0h\",");
    lines->append("                    item.address, item.data, expected_read(item.address)))");
    lines->append("            end");
    lines->append("            if (address_mapped(item.address))");
    lines->append("                check_outputs(item.address);");
    lines->append("            ++observed_count;");
    lines->append("        endfunction");
    lines->append("    endclass");
    lines->append(QString());
}

int appendSequence(QStringList *lines, const QSocMmioPlan &plan)
{
    const QString prefix = plan.moduleName + QStringLiteral("_uvm");
    lines->append(QString("    class %1_sequence extends uvm_sequence #(%1_item);").arg(prefix));
    lines->append(QString("        `uvm_object_utils(%1_sequence)").arg(prefix));
    lines->append(QString("        virtual %1_if vif;").arg(prefix));
    lines->append(QString());
    lines->append(QString("        function new(string name = \"%1_sequence\");").arg(prefix));
    lines->append("            super.new(name);");
    lines->append("        endfunction");
    lines->append(QString());
    lines->append(
        "        task send_write(addr_t address, data_t data, strb_t strobe, int unsigned order, "
        "bit hold_response);");
    lines->append(QString("            %1_item item;").arg(prefix));
    lines->append(
        QString("            item = %1_item::type_id::create(\"write_item\");").arg(prefix));
    lines->append("            start_item(item);");
    lines->append("            item.write = 1'b1;");
    lines->append("            item.address = address;");
    lines->append("            item.data = data;");
    lines->append("            item.strobe = strobe;");
    lines->append("            item.write_order = order;");
    lines->append("            item.hold_response = hold_response;");
    lines->append("            finish_item(item);");
    lines->append("        endtask");
    lines->append(QString());
    lines->append("        task send_read(addr_t address, bit hold_response);");
    lines->append(QString("            %1_item item;").arg(prefix));
    lines->append(
        QString("            item = %1_item::type_id::create(\"read_item\");").arg(prefix));
    lines->append("            start_item(item);");
    lines->append("            item.write = 1'b0;");
    lines->append("            item.address = address;");
    lines->append("            item.data = '0;");
    lines->append("            item.strobe = '0;");
    lines->append("            item.write_order = WRITE_TOGETHER;");
    lines->append("            item.hold_response = hold_response;");
    lines->append("            finish_item(item);");
    lines->append("        endtask");
    lines->append(QString());
    lines->append("        task body();");

    int  transactionCount = 0;
    bool heldRead         = false;
    bool heldWrite        = false;
    for (const QSocMmioRegisterPlan &reg : plan.registers) {
        lines->append(QString("            send_read(%1, %2);")
                          .arg(addressLiteral(plan, reg.byteOffset), heldRead ? "1'b0" : "1'b1"));
        heldRead = true;
        ++transactionCount;
    }

    qsizetype orderRegisterIndex = 0;
    for (qsizetype registerIndex = 0; registerIndex < plan.registers.size(); ++registerIndex) {
        if (writableMask(plan.registers.at(registerIndex)) != 0) {
            orderRegisterIndex = registerIndex;
            break;
        }
    }
    const QSocMmioRegisterPlan &orderRegister = plan.registers.at(orderRegisterIndex);
    for (quint32 order = 0; order < 3; ++order) {
        lines->append(QString("            send_write(%1, %2, '1, %3, %4);")
                          .arg(addressLiteral(plan, orderRegister.byteOffset))
                          .arg(dataLiteral(plan, writePattern(plan, orderRegisterIndex, order)))
                          .arg(order)
                          .arg(heldWrite ? "1'b0" : "1'b1"));
        heldWrite = true;
        lines->append(QString("            send_read(%1, 1'b0);")
                          .arg(addressLiteral(plan, orderRegister.byteOffset)));
        transactionCount += 2;
    }

    int writeOrder = 0;
    for (qsizetype registerIndex = 0; registerIndex < plan.registers.size(); ++registerIndex) {
        const QSocMmioRegisterPlan &reg       = plan.registers.at(registerIndex);
        const quint64               mask      = writableMask(reg);
        bool                        wroteLane = false;
        for (quint32 lane = 0; lane < plan.dataWidth / 8; ++lane) {
            if ((mask & (quint64(0xff) << (lane * 8))) == 0) {
                continue;
            }
            lines->append(QString("            send_write(%1, %2, %3, %4, 1'b0);")
                              .arg(addressLiteral(plan, reg.byteOffset))
                              .arg(dataLiteral(plan, writePattern(plan, registerIndex, lane)))
                              .arg(strobeLiteral(plan, quint64(1) << lane))
                              .arg(writeOrder++ % 3));
            lines->append(QString("            send_read(%1, 1'b0);")
                              .arg(addressLiteral(plan, reg.byteOffset)));
            transactionCount += 2;
            wroteLane = true;
        }
        if (!wroteLane) {
            lines->append(QString("            send_write(%1, %2, '1, %3, 1'b0);")
                              .arg(addressLiteral(plan, reg.byteOffset))
                              .arg(dataLiteral(plan, writePattern(plan, registerIndex, 0)))
                              .arg(writeOrder++ % 3));
            lines->append(QString("            send_read(%1, 1'b0);")
                              .arg(addressLiteral(plan, reg.byteOffset)));
            transactionCount += 2;
        }
    }

    for (qsizetype registerIndex = 0; registerIndex < plan.registers.size(); ++registerIndex) {
        const QSocMmioRegisterPlan &reg     = plan.registers.at(registerIndex);
        const QString               address = addressLiteral(plan, reg.byteOffset);
        for (const QSocMmioFieldPlan &field : reg.fields) {
            if (field.access != QSocMmioAccess::WriteOneClear) {
                continue;
            }
            /* One idle-bus pulse sets the bit. A zero leaves it, a one clears it. */
            const quint64 bit = fieldMask(field);
            lines->append("            @(negedge vif.clk_i);");
            lines->append(QString("            vif.%1 = 1'b1;").arg(field.inputPort));
            lines->append("            @(negedge vif.clk_i);");
            lines->append(QString("            vif.%1 = 1'b0;").arg(field.inputPort));
            lines->append(QString("            send_read(%1, 1'b0);").arg(address));
            lines->append(QString("            send_write(%1, %2, '1, %3, 1'b0);")
                              .arg(address, dataLiteral(plan, ~bit))
                              .arg(writeOrder++ % 3));
            lines->append(QString("            send_read(%1, 1'b0);").arg(address));
            lines->append(QString("            send_write(%1, %2, '1, %3, 1'b0);")
                              .arg(address, dataLiteral(plan, bit))
                              .arg(writeOrder++ % 3));
            lines->append(QString("            send_read(%1, 1'b0);").arg(address));
            transactionCount += 5;
        }
    }

    const quint64 errorData = plan.dataWidth == 64 ? UINT64_C(0xa55aa55a5aa55aa5)
                                                   : UINT64_C(0xa55aa55a);
    lines->append(QString("            send_write(%1, %2, '1, %3, 1'b0);")
                      .arg(addressLiteral(plan, 1))
                      .arg(dataLiteral(plan, errorData))
                      .arg(writeOrder++ % 3));
    lines->append(QString("            send_read(%1, 1'b0);").arg(addressLiteral(plan, 1)));
    transactionCount += 2;

    const std::optional<quint64> unmapped = unmappedAddress(plan);
    if (unmapped) {
        lines->append(QString("            send_write(%1, %2, '1, %3, 1'b0);")
                          .arg(addressLiteral(plan, *unmapped))
                          .arg(dataLiteral(plan, errorData))
                          .arg(writeOrder % 3));
        lines->append(
            QString("            send_read(%1, 1'b0);").arg(addressLiteral(plan, *unmapped)));
        transactionCount += 2;
    }
    for (const QSocMmioRegisterPlan &reg : plan.registers) {
        lines->append(
            QString("            send_read(%1, 1'b0);").arg(addressLiteral(plan, reg.byteOffset)));
        ++transactionCount;
    }
    lines->append("        endtask");
    lines->append("    endclass");
    lines->append(QString());
    return transactionCount;
}

void appendEnvironmentAndTest(QStringList *lines, const QSocMmioPlan &plan, int transactionCount)
{
    const QString prefix                   = plan.moduleName + QStringLiteral("_uvm");
    const QString interfaceName            = prefix + QStringLiteral("_if");
    const int     expectedTransactionCount = transactionCount * 2;
    lines->append(QString("    class %1_env extends uvm_env;").arg(prefix));
    lines->append(QString("        `uvm_component_utils(%1_env)").arg(prefix));
    lines->append(QString("        uvm_sequencer #(%1_item) sequencer;").arg(prefix));
    lines->append(QString("        %1_driver driver;").arg(prefix));
    lines->append(QString("        %1_monitor monitor;").arg(prefix));
    lines->append(QString("        %1_scoreboard scoreboard;").arg(prefix));
    lines->append(QString());
    lines->append(
        QString("        function new(string name = \"%1_env\", uvm_component parent = null);")
            .arg(prefix));
    lines->append("            super.new(name, parent);");
    lines->append("        endfunction");
    lines->append(QString());
    lines->append("        function void build_phase(uvm_phase phase);");
    lines->append("            super.build_phase(phase);");
    lines->append(
        QString("            sequencer = uvm_sequencer #(%1_item)::type_id::create(\"sequencer\", this);")
            .arg(prefix));
    lines->append(
        QString("            driver = %1_driver::type_id::create(\"driver\", this);").arg(prefix));
    lines->append(QString("            monitor = %1_monitor::type_id::create(\"monitor\", this);")
                      .arg(prefix));
    lines->append(
        QString("            scoreboard = %1_scoreboard::type_id::create(\"scoreboard\", this);")
            .arg(prefix));
    lines->append("        endfunction");
    lines->append(QString());
    lines->append("        function void connect_phase(uvm_phase phase);");
    lines->append("            super.connect_phase(phase);");
    lines->append("            driver.seq_item_port.connect(sequencer.seq_item_export);");
    lines->append("            monitor.observed.connect(scoreboard.analysis_export);");
    lines->append("        endfunction");
    lines->append("    endclass");
    lines->append(QString());
    lines->append(QString("    class %1_test extends uvm_test;").arg(prefix));
    lines->append(QString("        `uvm_component_utils(%1_test)").arg(prefix));
    lines->append(QString("        virtual %1 vif;").arg(interfaceName));
    lines->append(QString("        %1_env env;").arg(prefix));
    lines->append(QString());
    lines->append(
        QString("        function new(string name = \"%1_test\", uvm_component parent = null);")
            .arg(prefix));
    lines->append("            super.new(name, parent);");
    lines->append("        endfunction");
    lines->append(QString());
    lines->append("        function void build_phase(uvm_phase phase);");
    lines->append("            super.build_phase(phase);");
    lines->append(
        QString("            if (!uvm_config_db #(virtual %1)::get(this, \"\", \"vif\", vif))")
            .arg(interfaceName));
    lines->append(
        "                `uvm_fatal(\"NO_VIF\", \"MMIO virtual interface was not configured\")");
    lines->append(QString("            env = %1_env::type_id::create(\"env\", this);").arg(prefix));
    lines->append("        endfunction");
    lines->append(QString());
    lines->append("        task apply_reset();");
    lines->append("            vif.rst_ni = 1'b0;");
    lines->append("            env.scoreboard.reset_model();");
    lines->append("            repeat (RESET_CYCLES) @(posedge vif.clk_i);");
    lines->append("            @(negedge vif.clk_i);");
    lines->append("            vif.rst_ni = 1'b1;");
    lines->append("        endtask");
    lines->append(QString());
    lines->append("        task run_phase(uvm_phase phase);");
    lines->append(QString("            %1_sequence sequenceHandle;").arg(prefix));
    lines->append("            phase.raise_objection(this);");
    lines->append("            apply_reset();");
    lines->append(
        QString("            sequenceHandle = %1_sequence::type_id::create(\"initial_sequence\");")
            .arg(prefix));
    lines->append("            sequenceHandle.vif = vif;");
    lines->append("            sequenceHandle.start(env.sequencer);");
    lines->append("            apply_reset();");
    lines->append(
        QString(
            "            sequenceHandle = %1_sequence::type_id::create(\"post_reset_sequence\");")
            .arg(prefix));
    lines->append("            sequenceHandle.vif = vif;");
    lines->append("            sequenceHandle.start(env.sequencer);");
    lines->append("            repeat (DRAIN_CYCLES) @(posedge vif.clk_i);");
    lines->append("            if (!env.monitor.is_idle())");
    lines->append("                `uvm_fatal(\"DRAIN\", \"MMIO bus did not become idle\")");
    lines->append(QString("            if (env.scoreboard.observed_count != %1)")
                      .arg(expectedTransactionCount));
    lines->append(
        QStringLiteral(
            "                `uvm_fatal(\"COUNT\", $sformatf(\"observed %0d transactions, "
            "expected ")
        + QString::number(expectedTransactionCount) + QStringLiteral("\","));
    lines->append("                    env.scoreboard.observed_count))");
    lines->append(
        QStringLiteral("            `uvm_info(\"QSOC_UVM_PASS\", $sformatf(\"")
        + QString::number(plan.dataWidth)
        + QStringLiteral("-bit MMIO test passed at %0t\", $time), UVM_NONE)"));
    lines->append("            phase.drop_objection(this);");
    lines->append("        endtask");
    lines->append("    endclass");
}

QString buildPackage(const QSocMmioPlan &plan)
{
    const QString prefix = plan.moduleName + QStringLiteral("_uvm");
    QStringList   lines  = {
        "// Generated by QSoC. Do not edit.",
        QString("package %1_pkg;").arg(prefix),
        "    import uvm_pkg::*;",
        "    `include \"uvm_macros.svh\"",
        QString(),
        QString("    localparam int unsigned ADDR_WIDTH = %1;").arg(plan.addressWidth),
        QString("    localparam int unsigned DATA_WIDTH = %1;").arg(plan.dataWidth),
        QString("    localparam int unsigned STRB_WIDTH = %1;").arg(plan.dataWidth / 8),
        "    localparam int unsigned CHANNEL_TIMEOUT_CYCLES = 64;",
        "    localparam int unsigned RESET_CYCLES = 4;",
        "    localparam int unsigned DRAIN_CYCLES = 3;",
        "    localparam bit [1:0] RESP_OKAY = 2'b00;",
        "    localparam bit [1:0] RESP_SLVERR = 2'b10;",
        "    localparam int unsigned WRITE_TOGETHER = 0;",
        "    localparam int unsigned WRITE_AW_FIRST = 1;",
        "    localparam int unsigned WRITE_W_FIRST = 2;",
        "    typedef bit [ADDR_WIDTH-1:0] addr_t;",
        "    typedef bit [DATA_WIDTH-1:0] data_t;",
        "    typedef bit [STRB_WIDTH-1:0] strb_t;",
        QString(),
    };
    appendItem(&lines, plan);
    appendDriver(&lines, plan);
    appendMonitor(&lines, plan);
    appendScoreboard(&lines, plan);
    const int transactionCount = appendSequence(&lines, plan);
    appendEnvironmentAndTest(&lines, plan, transactionCount);
    lines.append("endpackage");
    return lines.join('\n') + '\n';
}

QStringList axiPortNames()
{
    return {
        "clk_i",         "rst_ni",        "s_axi_awaddr", "s_axi_awprot", "s_axi_awvalid",
        "s_axi_awready", "s_axi_wdata",   "s_axi_wstrb",  "s_axi_wvalid", "s_axi_wready",
        "s_axi_bresp",   "s_axi_bvalid",  "s_axi_bready", "s_axi_araddr", "s_axi_arprot",
        "s_axi_arvalid", "s_axi_arready", "s_axi_rdata",  "s_axi_rresp",  "s_axi_rvalid",
        "s_axi_rready",
    };
}

quint64 inputValue(const QSocMmioFieldPlan &field, int index)
{
    const quint64 pattern = UINT64_C(0xa55aa55a5aa55aa5) ^ (quint64(index) * 0x11111111);
    return pattern & widthMask(field.width);
}

QString buildTestbench(const QSocMmioPlan &plan)
{
    const QString prefix        = plan.moduleName + QStringLiteral("_uvm");
    const QString interfaceName = prefix + QStringLiteral("_if");
    const QString packageName   = prefix + QStringLiteral("_pkg");
    const QString testName      = prefix + QStringLiteral("_test");
    const QString topName       = prefix + QStringLiteral("_tb");
    QStringList   lines         = {
        "// Generated by QSoC. Do not edit.",
        QString("module %1;").arg(topName),
        "    timeunit 1ns;",
        "    timeprecision 1ps;",
        "    import uvm_pkg::*;",
        QString("    import %1::*;").arg(packageName),
        QString(),
        QString("    %1 bus();").arg(interfaceName),
        QString(),
        QString("    %1 dut (").arg(plan.moduleName),
    };
    QStringList ports = axiPortNames();
    for (const QSocMmioRegisterPlan &reg : plan.registers) {
        for (const QSocMmioFieldPlan &field : reg.fields) {
            if (!field.inputPort.isEmpty()) {
                ports.append(field.inputPort);
            }
            if (!field.outputPort.isEmpty()) {
                ports.append(field.outputPort);
            }
        }
    }
    for (qsizetype index = 0; index < ports.size(); ++index) {
        const QString suffix = index + 1 == ports.size() ? QString() : QString(",");
        lines.append(QString("        .%1(bus.%1)%2").arg(ports.at(index), suffix));
    }
    lines.append("    );");
    lines.append(QString());
    lines.append("    initial begin");
    lines.append("        bus.clk_i = 1'b0;");
    lines.append("        forever #5ns bus.clk_i = ~bus.clk_i;");
    lines.append("    end");
    QStringList inputInitializers;
    int         inputIndex = 0;
    for (const QSocMmioRegisterPlan &reg : plan.registers) {
        for (const QSocMmioFieldPlan &field : reg.fields) {
            if (!field.inputPort.isEmpty()) {
                const quint64 value = field.access == QSocMmioAccess::WriteOneClear
                                          ? 0
                                          : inputValue(field, inputIndex);
                ++inputIndex;
                inputInitializers.append(QString("        bus.%1 = %2;")
                                             .arg(field.inputPort, literal(field.width, value)));
            }
        }
    }
    if (!inputInitializers.isEmpty()) {
        lines.append(QString());
        lines.append("    initial begin");
        lines.append(inputInitializers);
        lines.append("    end");
    }
    lines.append(QString());
    lines.append("    initial begin");
    lines.append(QString("        uvm_config_db #(virtual %1)::set(null, \"*\", \"vif\", bus);")
                     .arg(interfaceName));
    lines.append(QString("        run_test(\"%1\");").arg(testName));
    lines.append("    end");
    lines.append(QString());
    lines.append("    initial begin");
    lines.append("        #1ms;");
    lines.append("        $fatal(1, \"QSOC_UVM_TIMEOUT\");");
    lines.append("    end");
    lines.append(QString());
    lines.append("    final begin");
    lines.append("        if (uvm_report_server::get_server().get_severity_count(UVM_ERROR) != 0");
    lines.append(
        "            || uvm_report_server::get_server().get_severity_count(UVM_FATAL) != 0)");
    lines.append("            $fatal(1, \"QSOC_UVM_FAILED\");");
    lines.append("    end");
    lines.append("endmodule");
    return lines.join('\n') + '\n';
}

QString buildFileList(const QSocMmioPlan &plan)
{
    return QString("%1.v\n%1_uvm_if.sv\n%1_uvm_pkg.sv\n%1_uvm_tb.sv\n").arg(plan.moduleName);
}

} // namespace

QSocMmioUvmCollateral QSocMmioUvm::generate(const QSocMmioPlan &plan)
{
    QSocMmioUvmCollateral collateral;
    collateral.interfaceSource = buildInterface(plan);
    collateral.packageSource   = buildPackage(plan);
    collateral.testbenchSource = buildTestbench(plan);
    collateral.fileList        = buildFileList(plan);
    return collateral;
}
